#!/usr/bin/env bash
# test-install-pr-markers.sh - Unit tests for the install-PR "docs-only"
# markers and the --skip-target-ci opt-in flag (issue #3333).
#
# The install PR generated by scripts/install/create-pr.sh carries three
# default markers that target CI can opt-in to detect:
#   - PR title prefix:        "chore(loom): Install Loom <version>"
#   - PR body marker line:    "loom-install: true"
#   - Commit trailer:         "Skip-CI-Hint: docs-only"
#
# The --skip-target-ci flag on install-loom.sh additionally prepends
# "[skip ci]" to the PR title and commit subject.
#
# Existing env-var overrides (PR_TITLE / PR_BODY / COMMIT_MSG) MUST remain
# composable: when set, the corresponding default is FULLY OVERRIDDEN — no
# marker injection occurs.
#
# Strategy: stub `git`, `gh`, and the forge-detect helper, then run
# create-pr.sh against an isolated temp dir. Capture the PR title, body, and
# commit message that *would* be sent to `gh pr create` / `git commit` by
# redirecting them through the stubs into temp files. No real PRs created.
#
# Usage:
#   bash defaults/scripts/tests/test-install-pr-markers.sh

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
CREATE_PR="$REPO_ROOT/scripts/install/create-pr.sh"
INSTALL_SH="$REPO_ROOT/scripts/install-loom.sh"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

TESTS_RUN=0
TESTS_PASSED=0
TESTS_FAILED=0

assert_contains() {
    local haystack="$1"
    local needle="$2"
    local msg="$3"
    TESTS_RUN=$((TESTS_RUN + 1))
    if [[ "$haystack" == *"$needle"* ]]; then
        TESTS_PASSED=$((TESTS_PASSED + 1))
        echo -e "  ${GREEN}PASS${NC}: $msg"
    else
        TESTS_FAILED=$((TESTS_FAILED + 1))
        echo -e "  ${RED}FAIL${NC}: $msg"
        echo "    Looking for: '$needle'"
        echo "    In:"
        printf '%s\n' "$haystack" | sed 's/^/      /'
    fi
}

assert_not_contains() {
    local haystack="$1"
    local needle="$2"
    local msg="$3"
    TESTS_RUN=$((TESTS_RUN + 1))
    if [[ "$haystack" != *"$needle"* ]]; then
        TESTS_PASSED=$((TESTS_PASSED + 1))
        echo -e "  ${GREEN}PASS${NC}: $msg"
    else
        TESTS_FAILED=$((TESTS_FAILED + 1))
        echo -e "  ${RED}FAIL${NC}: $msg"
        echo "    Unexpectedly found: '$needle'"
        echo "    In:"
        printf '%s\n' "$haystack" | sed 's/^/      /'
    fi
}

assert_starts_with() {
    local haystack="$1"
    local needle="$2"
    local msg="$3"
    TESTS_RUN=$((TESTS_RUN + 1))
    if [[ "$haystack" == "$needle"* ]]; then
        TESTS_PASSED=$((TESTS_PASSED + 1))
        echo -e "  ${GREEN}PASS${NC}: $msg"
    else
        TESTS_FAILED=$((TESTS_FAILED + 1))
        echo -e "  ${RED}FAIL${NC}: $msg"
        echo "    Expected start: '$needle'"
        echo "    Actual start:   '$(printf '%s' "$haystack" | head -1)'"
    fi
}

if [[ ! -f "$CREATE_PR" ]]; then
    echo "ERROR: $CREATE_PR not found" >&2
    exit 1
fi

if [[ ! -f "$INSTALL_SH" ]]; then
    echo "ERROR: $INSTALL_SH not found" >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# Test harness: stub `git`, `gh`, and forge-detect so create-pr.sh runs
# without making real network calls. Captured values land in $CAPTURE_DIR.
# ---------------------------------------------------------------------------

make_stub_env() {
    # $1 = path to a temp dir for stubs and capture files
    local stub_dir="$1"
    local capture_dir="$stub_dir/capture"
    mkdir -p "$stub_dir/bin" "$capture_dir"

    # --- git stub ---
    cat > "$stub_dir/bin/git" <<'EOF'
#!/usr/bin/env bash
# Minimal git stub for create-pr.sh tests.
case "$1" in
  config)
    # `git config --get remote.origin.url` — feed a github URL.
    if [[ "$2" == "--get" && "$3" == "remote.origin.url" ]]; then
      echo "https://github.com/test-owner/test-repo.git"
      exit 0
    fi
    exit 0
    ;;
  rev-parse)
    # `git rev-parse --abbrev-ref HEAD` — branch name
    echo "feature/loom-install-vTEST"
    exit 0
    ;;
  add)
    exit 0
    ;;
  diff)
    # `git diff --staged --quiet` — return non-zero so the script proceeds
    if [[ " $* " == *" --staged --quiet "* ]]; then
      exit 1  # non-zero => "there ARE staged changes, proceed"
    fi
    if [[ " $* " == *" --name-only "* ]]; then
      exit 0
    fi
    exit 0
    ;;
  commit)
    # Capture the commit message (-m "msg")
    while [[ $# -gt 0 ]]; do
      if [[ "$1" == "-m" ]]; then
        shift
        printf '%s' "$1" > "$CAPTURE_DIR/commit_msg"
        exit 0
      fi
      shift
    done
    exit 0
    ;;
  push)
    # Pretend the push succeeded; emit no workflow-scope error.
    echo "To https://github.com/test-owner/test-repo.git" >&2
    exit 0
    ;;
  reset)
    exit 0
    ;;
  ls-remote)
    exit 0
    ;;
esac
exit 0
EOF
    chmod +x "$stub_dir/bin/git"

    # --- gh stub ---
    cat > "$stub_dir/bin/gh" <<'EOF'
#!/usr/bin/env bash
# Minimal gh stub for create-pr.sh tests.
# Captures `gh pr create` arguments to $CAPTURE_DIR.
if [[ "$1" == "pr" && "$2" == "create" ]]; then
  shift 2
  # Walk args looking for --title / --body, capture them verbatim.
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --title)
        shift
        printf '%s' "$1" > "$CAPTURE_DIR/pr_title"
        ;;
      --body)
        shift
        printf '%s' "$1" > "$CAPTURE_DIR/pr_body"
        ;;
    esac
    shift
  done
  # Emit a fake PR URL on stdout so the caller's regex captures it.
  echo "https://github.com/test-owner/test-repo/pull/9999"
  exit 0
fi
exit 0
EOF
    chmod +x "$stub_dir/bin/gh"
}

# Run create-pr.sh in a stubbed environment and return captured values.
# Outputs nothing — caller reads files from $CAPTURE_DIR directly.
#
# Args:
#   $1 = scratch dir (stubs + capture)
#   $2... = extra env vars to set (e.g. PR_TITLE=foo)
run_create_pr() {
    local stub_dir="$1"
    shift
    local capture_dir="$stub_dir/capture"
    # Clear captures.
    rm -f "$capture_dir/pr_title" "$capture_dir/pr_body" "$capture_dir/commit_msg"

    # Make a worktree dir for create-pr.sh to cd into (it requires a real path).
    local worktree_dir="$stub_dir/worktree"
    mkdir -p "$worktree_dir"

    # Build the env command. We use `env -i` to start from a clean environment,
    # then pass KEY=VAL pairs as args. Doing this with `env -i ... "$@"` keeps
    # word-splitting safe (values with spaces survive).
    env -i \
        HOME="$HOME" \
        PATH="$stub_dir/bin:/usr/bin:/bin" \
        CAPTURE_DIR="$capture_dir" \
        LOOM_VERSION="0.8.0-test" \
        LOOM_COMMIT="testcommit" \
        FORCE_AUTO_MERGE=false \
        "$@" \
        bash "$CREATE_PR" "$worktree_dir" main \
        > "$stub_dir/stdout" 2> "$stub_dir/stderr" \
        || true
}

# ---------------------------------------------------------------------------
# Test cases
# ---------------------------------------------------------------------------

echo ""
echo "Testing install PR markers (issue #3333)..."
echo ""

# -----------------------------------------------------------------------------
# Group 1: Default markers (always on)
# -----------------------------------------------------------------------------
echo "Group 1: Default markers present (no overrides)"

STUB_DIR1=$(mktemp -d /tmp/loom-pr-markers-1.XXXXXX)
trap 'rm -rf "$STUB_DIR1"' EXIT
make_stub_env "$STUB_DIR1"
run_create_pr "$STUB_DIR1"

PR_TITLE_OUT=$(cat "$STUB_DIR1/capture/pr_title" 2>/dev/null || echo "")
PR_BODY_OUT=$(cat "$STUB_DIR1/capture/pr_body" 2>/dev/null || echo "")
COMMIT_MSG_OUT=$(cat "$STUB_DIR1/capture/commit_msg" 2>/dev/null || echo "")

assert_starts_with "$PR_TITLE_OUT" "chore(loom): " \
    "PR title starts with 'chore(loom): ' prefix"
assert_contains "$PR_TITLE_OUT" "Install Loom 0.8.0-test" \
    "PR title contains 'Install Loom <version>'"
assert_not_contains "$PR_TITLE_OUT" "[skip ci]" \
    "PR title does NOT contain '[skip ci]' by default"

# Body marker line must be on its own line (separator-isolated).
assert_contains "$PR_BODY_OUT" $'\nloom-install: true\n' \
    "PR body contains 'loom-install: true' on its own line"
assert_contains "$PR_BODY_OUT" $'\ndocs-only: true\n' \
    "PR body contains 'docs-only: true' on its own line"

# Commit trailer must be present.
assert_contains "$COMMIT_MSG_OUT" $'\nSkip-CI-Hint: docs-only' \
    "Commit message contains 'Skip-CI-Hint: docs-only' trailer on its own line"
assert_starts_with "$COMMIT_MSG_OUT" "chore(loom): " \
    "Commit subject starts with 'chore(loom): ' prefix"
assert_not_contains "$COMMIT_MSG_OUT" "[skip ci]" \
    "Commit subject does NOT contain '[skip ci]' by default"

rm -rf "$STUB_DIR1"
trap - EXIT

# -----------------------------------------------------------------------------
# Group 2: --skip-target-ci (SKIP_TARGET_CI=true) adds [skip ci] prefix
# -----------------------------------------------------------------------------
echo ""
echo "Group 2: SKIP_TARGET_CI=true adds [skip ci] prefix"

STUB_DIR2=$(mktemp -d /tmp/loom-pr-markers-2.XXXXXX)
trap 'rm -rf "$STUB_DIR2"' EXIT
make_stub_env "$STUB_DIR2"
run_create_pr "$STUB_DIR2" "SKIP_TARGET_CI=true"

PR_TITLE_OUT=$(cat "$STUB_DIR2/capture/pr_title" 2>/dev/null || echo "")
PR_BODY_OUT=$(cat "$STUB_DIR2/capture/pr_body" 2>/dev/null || echo "")
COMMIT_MSG_OUT=$(cat "$STUB_DIR2/capture/commit_msg" 2>/dev/null || echo "")

assert_starts_with "$PR_TITLE_OUT" "[skip ci] chore(loom): " \
    "PR title starts with '[skip ci] chore(loom): ' under --skip-target-ci"
assert_starts_with "$COMMIT_MSG_OUT" "[skip ci] chore(loom): " \
    "Commit subject starts with '[skip ci] chore(loom): ' under --skip-target-ci"

# Other markers MUST still be present (composability).
assert_contains "$PR_BODY_OUT" $'\nloom-install: true\n' \
    "PR body still contains 'loom-install: true' under --skip-target-ci"
assert_contains "$COMMIT_MSG_OUT" $'\nSkip-CI-Hint: docs-only' \
    "Commit still carries 'Skip-CI-Hint: docs-only' trailer under --skip-target-ci"

rm -rf "$STUB_DIR2"
trap - EXIT

# -----------------------------------------------------------------------------
# Group 3: PR_TITLE / PR_BODY / COMMIT_MSG env overrides take precedence
# -----------------------------------------------------------------------------
echo ""
echo "Group 3: Env-var overrides fully replace defaults (no marker injection)"

STUB_DIR3=$(mktemp -d /tmp/loom-pr-markers-3.XXXXXX)
trap 'rm -rf "$STUB_DIR3"' EXIT
make_stub_env "$STUB_DIR3"
run_create_pr "$STUB_DIR3" \
    "PR_TITLE=Custom title verbatim" \
    "PR_BODY=Custom body verbatim" \
    "COMMIT_MSG=Custom commit subject"

PR_TITLE_OUT=$(cat "$STUB_DIR3/capture/pr_title" 2>/dev/null || echo "")
PR_BODY_OUT=$(cat "$STUB_DIR3/capture/pr_body" 2>/dev/null || echo "")
COMMIT_MSG_OUT=$(cat "$STUB_DIR3/capture/commit_msg" 2>/dev/null || echo "")

# Each env-set value MUST be present verbatim.
assert_contains "$PR_TITLE_OUT" "Custom title verbatim" \
    "PR_TITLE override appears verbatim"
assert_contains "$PR_BODY_OUT" "Custom body verbatim" \
    "PR_BODY override appears verbatim"
assert_contains "$COMMIT_MSG_OUT" "Custom commit subject" \
    "COMMIT_MSG override appears verbatim"

# Defaults MUST NOT have been injected on top.
assert_not_contains "$PR_TITLE_OUT" "chore(loom)" \
    "PR_TITLE override prevents 'chore(loom)' default prefix"
assert_not_contains "$PR_BODY_OUT" "loom-install: true" \
    "PR_BODY override prevents 'loom-install: true' marker injection"
assert_not_contains "$COMMIT_MSG_OUT" "Skip-CI-Hint" \
    "COMMIT_MSG override prevents 'Skip-CI-Hint' trailer injection"

rm -rf "$STUB_DIR3"
trap - EXIT

# -----------------------------------------------------------------------------
# Group 4: --skip-target-ci flag is parsed by install-loom.sh argv
# -----------------------------------------------------------------------------
echo ""
echo "Group 4: install-loom.sh --help mentions --skip-target-ci"

HELP_OUT=$(bash "$INSTALL_SH" --help 2>&1 || true)

assert_contains "$HELP_OUT" "--skip-target-ci" \
    "install-loom.sh --help lists the --skip-target-ci flag"
assert_contains "$HELP_OUT" "chore(loom)" \
    "install-loom.sh --help mentions the chore(loom) title prefix"
assert_contains "$HELP_OUT" "loom-install: true" \
    "install-loom.sh --help mentions the loom-install body marker"
assert_contains "$HELP_OUT" "Skip-CI-Hint" \
    "install-loom.sh --help mentions the Skip-CI-Hint commit trailer"

# -----------------------------------------------------------------------------
# Group 5: ci-integration.md exists in defaults/docs/
# -----------------------------------------------------------------------------
echo ""
echo "Group 5: Integration doc exists"

CI_DOC="$REPO_ROOT/defaults/docs/ci-integration.md"
TESTS_RUN=$((TESTS_RUN + 1))
if [[ -f "$CI_DOC" ]]; then
    TESTS_PASSED=$((TESTS_PASSED + 1))
    echo -e "  ${GREEN}PASS${NC}: defaults/docs/ci-integration.md exists"
    # Sanity-check the doc mentions key things.
    DOC_CONTENT=$(cat "$CI_DOC")
    assert_contains "$DOC_CONTENT" "paths-ignore" \
        "Integration doc mentions paths-ignore"
    assert_contains "$DOC_CONTENT" "chore(loom)" \
        "Integration doc mentions chore(loom) title prefix"
    assert_contains "$DOC_CONTENT" "loom-install: true" \
        "Integration doc mentions loom-install body marker"
    assert_contains "$DOC_CONTENT" "Skip-CI-Hint" \
        "Integration doc mentions Skip-CI-Hint commit trailer"
    assert_contains "$DOC_CONTENT" "--skip-target-ci" \
        "Integration doc documents --skip-target-ci flag"
else
    TESTS_FAILED=$((TESTS_FAILED + 1))
    echo -e "  ${RED}FAIL${NC}: defaults/docs/ci-integration.md missing"
fi

# -----------------------------------------------------------------------------
# Summary
# -----------------------------------------------------------------------------
echo ""
echo "============================================================"
echo "Test summary: $TESTS_PASSED/$TESTS_RUN passed ($TESTS_FAILED failed)"
echo "============================================================"

if [[ "$TESTS_FAILED" -gt 0 ]]; then
    exit 1
fi
exit 0
