use crate::{keywords::Keyword, token::Token};

/// Map a keyword string (uppercase) to its corresponding Token.
/// Returns Token::Identifier if the string is not a recognized keyword.
pub(super) fn map_keyword(upper_text: String) -> Token {
    match upper_text.as_str() {
        "SELECT" => Token::Keyword(Keyword::Select),
        "DISTINCT" => Token::Keyword(Keyword::Distinct),
        "FROM" => Token::Keyword(Keyword::From),
        "WHERE" => Token::Keyword(Keyword::Where),
        "INSERT" => Token::Keyword(Keyword::Insert),
        "INTO" => Token::Keyword(Keyword::Into),
        "REPLACE" => Token::Keyword(Keyword::Replace),
        "IGNORE" => Token::Keyword(Keyword::Ignore),
        "UPDATE" => Token::Keyword(Keyword::Update),
        "DELETE" => Token::Keyword(Keyword::Delete),
        "DUPLICATE" => Token::Keyword(Keyword::Duplicate),
        "CREATE" => Token::Keyword(Keyword::Create),
        "TABLE" => Token::Keyword(Keyword::Table),
        "TRUNCATE" => Token::Keyword(Keyword::Truncate),
        "DROP" => Token::Keyword(Keyword::Drop),
        "ADD" => Token::Keyword(Keyword::Add),
        "ALTER" => Token::Keyword(Keyword::Alter),
        "AND" => Token::Keyword(Keyword::And),
        "OR" => Token::Keyword(Keyword::Or),
        "NOT" => Token::Keyword(Keyword::Not),
        "NULL" => Token::Keyword(Keyword::Null),
        "TRUE" => Token::Keyword(Keyword::True),
        "FALSE" => Token::Keyword(Keyword::False),
        "AS" => Token::Keyword(Keyword::As),
        "JOIN" => Token::Keyword(Keyword::Join),
        "LEFT" => Token::Keyword(Keyword::Left),
        "RIGHT" => Token::Keyword(Keyword::Right),
        "INNER" => Token::Keyword(Keyword::Inner),
        "OUTER" => Token::Keyword(Keyword::Outer),
        "CROSS" => Token::Keyword(Keyword::Cross),
        "FULL" => Token::Keyword(Keyword::Full),
        "NATURAL" => Token::Keyword(Keyword::Natural),
        "ON" => Token::Keyword(Keyword::On),
        "GROUP" => Token::Keyword(Keyword::Group),
        "BY" => Token::Keyword(Keyword::By),
        // OLAP extensions for GROUP BY
        "ROLLUP" => Token::Keyword(Keyword::Rollup),
        "CUBE" => Token::Keyword(Keyword::Cube),
        "SETS" => Token::Keyword(Keyword::Sets),
        "GROUPING" => Token::Keyword(Keyword::Grouping),
        "GROUPING_ID" => Token::Keyword(Keyword::GroupingId),
        "HAVING" => Token::Keyword(Keyword::Having),
        "ORDER" => Token::Keyword(Keyword::Order),
        "ASC" => Token::Keyword(Keyword::Asc),
        "DESC" => Token::Keyword(Keyword::Desc),
        "LIMIT" => Token::Keyword(Keyword::Limit),
        "OFFSET" => Token::Keyword(Keyword::Offset),
        "SET" => Token::Keyword(Keyword::Set),
        "VALUES" => Token::Keyword(Keyword::Values),
        "IN" => Token::Keyword(Keyword::In),
        "BETWEEN" => Token::Keyword(Keyword::Between),
        "ASYMMETRIC" => Token::Keyword(Keyword::Asymmetric),
        "SYMMETRIC" => Token::Keyword(Keyword::Symmetric),
        "LIKE" => Token::Keyword(Keyword::Like),
        "EXISTS" => Token::Keyword(Keyword::Exists),
        "IF" => Token::Keyword(Keyword::If),
        "IS" => Token::Keyword(Keyword::Is),
        "ALL" => Token::Keyword(Keyword::All),
        "ANY" => Token::Keyword(Keyword::Any),
        "SOME" => Token::Keyword(Keyword::Some),
        "UNION" => Token::Keyword(Keyword::Union),
        "INTERSECT" => Token::Keyword(Keyword::Intersect),
        "EXCEPT" => Token::Keyword(Keyword::Except),
        "WITH" => Token::Keyword(Keyword::With),
        "RECURSIVE" => Token::Keyword(Keyword::Recursive),
        "DATE" => Token::Keyword(Keyword::Date),
        "DEFAULT" => Token::Keyword(Keyword::Default),
        "TIME" => Token::Keyword(Keyword::Time),
        "TIMESTAMP" => Token::Keyword(Keyword::Timestamp),
        "INTERVAL" => Token::Keyword(Keyword::Interval),
        "CAST" => Token::Keyword(Keyword::Cast),
        // CASE expression keywords
        "CASE" => Token::Keyword(Keyword::Case),
        "WHEN" => Token::Keyword(Keyword::When),
        "THEN" => Token::Keyword(Keyword::Then),
        "ELSE" => Token::Keyword(Keyword::Else),
        "END" => Token::Keyword(Keyword::End),
        // Window function keywords
        "OVER" => Token::Keyword(Keyword::Over),
        "PARTITION" => Token::Keyword(Keyword::Partition),
        "ROWS" => Token::Keyword(Keyword::Rows),
        "RANGE" => Token::Keyword(Keyword::Range),
        "PRECEDING" => Token::Keyword(Keyword::Preceding),
        "FOLLOWING" => Token::Keyword(Keyword::Following),
        "UNBOUNDED" => Token::Keyword(Keyword::Unbounded),
        "CURRENT" => Token::Keyword(Keyword::Current),
        "CURRENT_DATE" => Token::Keyword(Keyword::CurrentDate),
        "CURRENT_TIME" => Token::Keyword(Keyword::CurrentTime),
        "CURRENT_TIMESTAMP" => Token::Keyword(Keyword::CurrentTimestamp),
        // Note: ROW_NUMBER, RANK, DENSE_RANK, NTILE, LAG, LEAD are treated as
        // identifiers (function names), not keywords. They are classified as
        // window functions by the parser's classify_window_function() method.
        // Transaction keywords
        "BEGIN" => Token::Keyword(Keyword::Begin),
        "COLUMN" => Token::Keyword(Keyword::Column),
        "COMMIT" => Token::Keyword(Keyword::Commit),
        "CONSTRAINT" => Token::Keyword(Keyword::Constraint),
        "RENAME" => Token::Keyword(Keyword::Rename),
        "MODIFY" => Token::Keyword(Keyword::Modify),
        "CHANGE" => Token::Keyword(Keyword::Change),
        "ROLLBACK" => Token::Keyword(Keyword::Rollback),
        "START" => Token::Keyword(Keyword::Start),
        "TRANSACTION" => Token::Keyword(Keyword::Transaction),
        // Schema keywords
        "SCHEMA" => Token::Keyword(Keyword::Schema),
        "CASCADE" => Token::Keyword(Keyword::Cascade),
        "RESTRICT" => Token::Keyword(Keyword::Restrict),
        "SAVEPOINT" => Token::Keyword(Keyword::Savepoint),
        "RELEASE" => Token::Keyword(Keyword::Release),
        "TO" => Token::Keyword(Keyword::To),
        // Constraint keywords
        "PRIMARY" => Token::Keyword(Keyword::Primary),
        "FOREIGN" => Token::Keyword(Keyword::Foreign),
        "KEY" => Token::Keyword(Keyword::Key),
        "UNIQUE" => Token::Keyword(Keyword::Unique),
        "CHECK" => Token::Keyword(Keyword::Check),
        "REFERENCES" => Token::Keyword(Keyword::References),
        "ACTION" => Token::Keyword(Keyword::Action),
        // TRIM function keywords
        "BOTH" => Token::Keyword(Keyword::Both),
        "LEADING" => Token::Keyword(Keyword::Leading),
        "TRAILING" => Token::Keyword(Keyword::Trailing),
        // MySQL arithmetic operators
        "DIV" => Token::Keyword(Keyword::Div),
        // Data type keywords
        "VARYING" => Token::Keyword(Keyword::Varying),
        "CHARACTERS" => Token::Keyword(Keyword::Characters),
        "OCTETS" => Token::Keyword(Keyword::Octets),
        "USING" => Token::Keyword(Keyword::Using),
        // SUBSTRING function keywords
        "FOR" => Token::Keyword(Keyword::For),
        // GRANT keywords
        "GRANT" => Token::Keyword(Keyword::Grant),
        "PRIVILEGES" => Token::Keyword(Keyword::Privileges),
        "USAGE" => Token::Keyword(Keyword::Usage),
        "OPTION" => Token::Keyword(Keyword::Option),
        // REVOKE keywords
        "REVOKE" => Token::Keyword(Keyword::Revoke),
        "GRANTED" => Token::Keyword(Keyword::Granted),
        // Advanced privilege keywords
        "EXECUTE" => Token::Keyword(Keyword::Execute),
        "TRIGGER" => Token::Keyword(Keyword::Trigger),
        "UNDER" => Token::Keyword(Keyword::Under),
        // Role management keywords
        "ROLE" => Token::Keyword(Keyword::Role),
        // Advanced SQL object keywords
        "DOMAIN" => Token::Keyword(Keyword::Domain),
        "SEQUENCE" => Token::Keyword(Keyword::Sequence),
        "TYPE" => Token::Keyword(Keyword::Type),
        "COLLATION" => Token::Keyword(Keyword::Collation),
        "CHARACTER" => Token::Keyword(Keyword::Character),
        "TRANSLATION" => Token::Keyword(Keyword::Translation),
        "SPECIFIC" => Token::Keyword(Keyword::Specific),
        "VIEW" => Token::Keyword(Keyword::View),
        "INDEX" => Token::Keyword(Keyword::Index),
        "ANALYZE" => Token::Keyword(Keyword::Analyze),
        "REINDEX" => Token::Keyword(Keyword::Reindex),
        "ASSERTION" => Token::Keyword(Keyword::Assertion),
        // Trigger-specific keywords
        "BEFORE" => Token::Keyword(Keyword::Before),
        "AFTER" => Token::Keyword(Keyword::After),
        "INSTEAD" => Token::Keyword(Keyword::Instead),
        "OF" => Token::Keyword(Keyword::Of),
        "EACH" => Token::Keyword(Keyword::Each),
        "ROW" => Token::Keyword(Keyword::Row),
        "STATEMENT" => Token::Keyword(Keyword::Statement),
        "ENABLE" => Token::Keyword(Keyword::Enable),
        "DISABLE" => Token::Keyword(Keyword::Disable),
        // SEQUENCE specific keywords
        "INCREMENT" => Token::Keyword(Keyword::Increment),
        "MINVALUE" => Token::Keyword(Keyword::Minvalue),
        "MAXVALUE" => Token::Keyword(Keyword::Maxvalue),
        "CYCLE" => Token::Keyword(Keyword::Cycle),
        "NO" => Token::Keyword(Keyword::No),
        "RESTART" => Token::Keyword(Keyword::Restart),
        "NEXT" => Token::Keyword(Keyword::Next),
        // Session configuration keywords (SQL:1999)
        "CATALOG" => Token::Keyword(Keyword::Catalog),
        "NAMES" => Token::Keyword(Keyword::Names),
        "ZONE" => Token::Keyword(Keyword::Zone),
        "LOCAL" => Token::Keyword(Keyword::Local),
        "SESSION" => Token::Keyword(Keyword::Session),
        "GLOBAL" => Token::Keyword(Keyword::Global),
        // Interval unit keywords
        "YEAR" => Token::Keyword(Keyword::Year),
        "QUARTER" => Token::Keyword(Keyword::Quarter),
        "MONTH" => Token::Keyword(Keyword::Month),
        "WEEK" => Token::Keyword(Keyword::Week),
        "DAY" => Token::Keyword(Keyword::Day),
        "HOUR" => Token::Keyword(Keyword::Hour),
        "MINUTE" => Token::Keyword(Keyword::Minute),
        "SECOND" => Token::Keyword(Keyword::Second),
        "MICROSECOND" => Token::Keyword(Keyword::Microsecond),
        // Callable object keywords (functions, procedures, methods)
        "FUNCTION" => Token::Keyword(Keyword::Function),
        "PROCEDURE" => Token::Keyword(Keyword::Procedure),
        "CALL" => Token::Keyword(Keyword::Call),
        "ROUTINE" => Token::Keyword(Keyword::Routine),
        "METHOD" => Token::Keyword(Keyword::Method),
        "CONSTRUCTOR" => Token::Keyword(Keyword::Constructor),
        "STATIC" => Token::Keyword(Keyword::Static),
        "INSTANCE" => Token::Keyword(Keyword::Instance),
        // Procedure/Function parameter modes
        "OUT" => Token::Keyword(Keyword::Out),
        "INOUT" => Token::Keyword(Keyword::InOut),
        // Procedure/Function keywords
        "RETURNS" => Token::Keyword(Keyword::Returns),
        "WHILE" => Token::Keyword(Keyword::While),
        "DO" => Token::Keyword(Keyword::Do),
        "LOOP" => Token::Keyword(Keyword::Loop),
        "REPEAT" => Token::Keyword(Keyword::Repeat),
        "UNTIL" => Token::Keyword(Keyword::Until),
        "RETURN" => Token::Keyword(Keyword::Return),
        "LEAVE" => Token::Keyword(Keyword::Leave),
        "ITERATE" => Token::Keyword(Keyword::Iterate),
        // Procedure/Function characteristics (Phase 6)
        "DETERMINISTIC" => Token::Keyword(Keyword::Deterministic),
        "LANGUAGE" => Token::Keyword(Keyword::Language),
        "SQL" => Token::Keyword(Keyword::Sql),
        "SECURITY" => Token::Keyword(Keyword::Security),
        "DEFINER" => Token::Keyword(Keyword::Definer),
        "INVOKER" => Token::Keyword(Keyword::Invoker),
        // Internationalization keywords (SQL:1999)
        "GET" => Token::Keyword(Keyword::Get),
        "PAD" => Token::Keyword(Keyword::Pad),
        "SPACE" => Token::Keyword(Keyword::Space),
        "COLLATE" => Token::Keyword(Keyword::Collate),
        "COMMENT" => Token::Keyword(Keyword::Comment),
        // CURSOR keywords
        "DECLARE" => Token::Keyword(Keyword::Declare),
        "CURSOR" => Token::Keyword(Keyword::Cursor),
        "INSENSITIVE" => Token::Keyword(Keyword::Insensitive),
        "SCROLL" => Token::Keyword(Keyword::Scroll),
        "HOLD" => Token::Keyword(Keyword::Hold),
        "WITHOUT" => Token::Keyword(Keyword::Without),
        "READ" => Token::Keyword(Keyword::Read),
        "ONLY" => Token::Keyword(Keyword::Only),
        "WRITE" => Token::Keyword(Keyword::Write),
        "OIDS" => Token::Keyword(Keyword::Oids),
        "OPEN" => Token::Keyword(Keyword::Open),
        "FETCH" => Token::Keyword(Keyword::Fetch),
        "CLOSE" => Token::Keyword(Keyword::Close),
        "PRIOR" => Token::Keyword(Keyword::Prior),
        "FIRST" => Token::Keyword(Keyword::First),
        "LAST" => Token::Keyword(Keyword::Last),
        "ABSOLUTE" => Token::Keyword(Keyword::Absolute),
        "RELATIVE" => Token::Keyword(Keyword::Relative),
        "SERIALIZABLE" => Token::Keyword(Keyword::Serializable),
        "ISOLATION" => Token::Keyword(Keyword::Isolation),
        "LEVEL" => Token::Keyword(Keyword::Level),
        // MySQL table option keywords
        "KEY_BLOCK_SIZE" => Token::Keyword(Keyword::KeyBlockSize),
        "CONNECTION" => Token::Keyword(Keyword::Connection),
        "INSERT_METHOD" => Token::Keyword(Keyword::InsertMethod),
        "ROW_FORMAT" => Token::Keyword(Keyword::RowFormat),
        "DELAY_KEY_WRITE" => Token::Keyword(Keyword::DelayKeyWrite),
        "TABLE_CHECKSUM" => Token::Keyword(Keyword::TableChecksum),
        "CHECKSUM" => Token::Keyword(Keyword::Checksum),
        "STATS_SAMPLE_PAGES" => Token::Keyword(Keyword::StatsSamplePages),
        "PASSWORD" => Token::Keyword(Keyword::Password),
        "AVG_ROW_LENGTH" => Token::Keyword(Keyword::AvgRowLength),
        "MIN_ROWS" => Token::Keyword(Keyword::MinRows),
        "MAX_ROWS" => Token::Keyword(Keyword::MaxRows),
        "SECONDARY_ENGINE" => Token::Keyword(Keyword::SecondaryEngine),
        // MySQL table option values
        "DYNAMIC" => Token::Keyword(Keyword::Dynamic),
        "FIXED" => Token::Keyword(Keyword::Fixed),
        "COMPRESSED" => Token::Keyword(Keyword::Compressed),
        "REDUNDANT" => Token::Keyword(Keyword::Redundant),
        "COMPACT" => Token::Keyword(Keyword::Compact),
        // Full-text search keywords
        "FULLTEXT" => Token::Keyword(Keyword::Fulltext),
        "MATCH" => Token::Keyword(Keyword::Match),
        "AGAINST" => Token::Keyword(Keyword::Against),
        "BOOLEAN" => Token::Keyword(Keyword::Boolean),
        "EXPANSION" => Token::Keyword(Keyword::Expansion),
        "MODE" => Token::Keyword(Keyword::Mode),
        "QUERY" => Token::Keyword(Keyword::Query),
        // Spatial index keywords
        "SPATIAL" => Token::Keyword(Keyword::Spatial),
        // Database introspection keywords
        "SHOW" => Token::Keyword(Keyword::Show),
        "DESCRIBE" => Token::Keyword(Keyword::Describe),
        "DATABASES" => Token::Keyword(Keyword::Databases),
        "TABLES" => Token::Keyword(Keyword::Tables),
        "COLUMNS" => Token::Keyword(Keyword::Columns),
        "FIELDS" => Token::Keyword(Keyword::Fields),
        "INDEXES" => Token::Keyword(Keyword::Indexes),
        "KEYS" => Token::Keyword(Keyword::Keys),
        // Auto-increment keywords (MySQL and SQLite)
        "AUTO_INCREMENT" => Token::Keyword(Keyword::AutoIncrement),
        "AUTOINCREMENT" => Token::Keyword(Keyword::AutoIncrement),
        // Temporary object keywords (SQLite)
        "TEMP" => Token::Keyword(Keyword::Temp),
        "TEMPORARY" => Token::Keyword(Keyword::Temporary),
        // VibeSQL storage format keywords
        "STORAGE" => Token::Keyword(Keyword::Storage),
        "COLUMNAR" => Token::Keyword(Keyword::Columnar),
        _ => Token::Identifier(upper_text), // Regular identifiers are normalized to uppercase
    }
}
