//! ORDER BY sorting logic

use std::{borrow::Cow, cmp::Ordering};

#[cfg(feature = "parallel")]
use rayon::slice::ParallelSliceMut;

use super::grouping::compare_sql_values;
#[cfg(feature = "parallel")]
use super::parallel::ParallelConfig;
use crate::{
    errors::ExecutorError, evaluator::CombinedExpressionEvaluator, schema::CombinedSchema,
};

/// Result of extracting a column position from an ORDER BY expression
#[derive(Debug, Clone, Copy)]
enum ColumnPositionResult {
    /// A valid positive column position (1-indexed)
    Position(i64),
    /// A negative column position (always invalid, but we track it for error reporting)
    Negative(i64),
    /// Not a column position expression
    NotAPosition,
}

/// Extracts a numeric column position from an ORDER BY expression.
///
/// Handles:
/// - `ORDER BY N` - Integer literal → Position(N)
/// - `ORDER BY +N` - Unary plus with integer → Position(N) (#4418)
/// - `ORDER BY -N` - Unary minus with integer → Negative(N)
/// - Other expressions → NotAPosition
fn extract_column_position(expr: &vibesql_ast::Expression) -> ColumnPositionResult {
    match expr {
        // Direct integer literal: ORDER BY 1, ORDER BY 2, etc.
        vibesql_ast::Expression::Literal(vibesql_types::SqlValue::Integer(pos)) => {
            ColumnPositionResult::Position(*pos)
        }
        // Unary operator with integer
        vibesql_ast::Expression::UnaryOp { op, expr } => {
            if let vibesql_ast::Expression::Literal(vibesql_types::SqlValue::Integer(pos)) =
                expr.as_ref()
            {
                match op {
                    // ORDER BY +N: treat as ORDER BY N (#4418)
                    vibesql_ast::UnaryOperator::Plus => ColumnPositionResult::Position(*pos),
                    // ORDER BY -N: always invalid
                    vibesql_ast::UnaryOperator::Minus => ColumnPositionResult::Negative(*pos),
                    _ => ColumnPositionResult::NotAPosition,
                }
            } else {
                ColumnPositionResult::NotAPosition
            }
        }
        _ => ColumnPositionResult::NotAPosition,
    }
}

/// Validates a column position and returns an error if out of range.
fn validate_column_position(
    pos: i64,
    column_count: usize,
    term_index: usize,
) -> Result<usize, ExecutorError> {
    if pos <= 0 || (pos as usize) > column_count {
        return Err(ExecutorError::OrderByOutOfRange {
            term_position: term_index + 1, // Convert to 1-indexed for error message
            column_number: pos,
            select_list_len: column_count,
        });
    }
    Ok((pos as usize) - 1) // Convert to 0-indexed
}

/// Resolves a column position to a column name for aggregate queries.
///
/// For aggregate queries, we simply look up the alias/expression at the given position
/// in the SELECT list without wildcard expansion (aggregates don't typically use wildcards).
fn resolve_position_to_column_name(
    idx: usize,
    select_list: &[vibesql_ast::SelectItem],
) -> Option<String> {
    if let vibesql_ast::SelectItem::Expression { expr, alias, .. } = &select_list[idx] {
        Some(if let Some(alias_name) = alias {
            alias_name.clone()
        } else if let vibesql_ast::Expression::ColumnRef(col_id) = expr {
            col_id.column_canonical().to_string()
        } else if let vibesql_ast::Expression::AggregateFunction { name, .. } = expr {
            // For aggregate functions without alias, use the function name (lowercase)
            // This matches the schema column name generated by the aggregate executor
            name.to_lowercase()
        } else {
            format!("col{}", idx + 1)
        })
    } else {
        None
    }
}

/// Result of resolving a column position with wildcard expansion
enum ResolvedPosition<'a> {
    /// The expression at the position (for regular SELECT items)
    Expression(&'a vibesql_ast::Expression),
    /// A column name resolved from a wildcard expansion
    ColumnName(String),
    /// Position not found (shouldn't happen if validation passed)
    NotFound,
}

/// Resolves a column position to an expression or column name, handling wildcard expansion.
///
/// This handles SELECT lists that may contain wildcards (`*`) or qualified wildcards (`table.*`)
/// which expand to multiple columns. The position is 0-indexed.
fn resolve_position_with_wildcards<'a>(
    target_col: usize,
    select_list: &'a [vibesql_ast::SelectItem],
    schema: Option<&CombinedSchema>,
) -> ResolvedPosition<'a> {
    let mut current_col = 0;

    for item in select_list {
        match item {
            vibesql_ast::SelectItem::Wildcard { .. } => {
                // Count how many columns this wildcard expands to
                let wildcard_cols = if let Some(s) = schema {
                    s.table_schemas.values().map(|(_, ts)| ts.columns.len()).sum()
                } else {
                    1
                };

                if target_col < current_col + wildcard_cols {
                    // The position is within this wildcard's expanded columns
                    if let Some(s) = schema {
                        let offset_in_wildcard = target_col - current_col;
                        // Collect all columns from all tables in schema order
                        let mut all_columns: Vec<(usize, String)> = Vec::new();
                        for (start_idx, table_schema) in s.table_schemas.values() {
                            for (i, col) in table_schema.columns.iter().enumerate() {
                                all_columns.push((start_idx + i, col.name.clone()));
                            }
                        }
                        all_columns.sort_by_key(|(idx, _)| *idx);

                        if offset_in_wildcard < all_columns.len() {
                            return ResolvedPosition::ColumnName(
                                all_columns[offset_in_wildcard].1.clone(),
                            );
                        }
                    }
                    return ResolvedPosition::NotFound;
                }
                current_col += wildcard_cols;
            }
            vibesql_ast::SelectItem::QualifiedWildcard { qualifier, .. } => {
                // Count how many columns this qualified wildcard expands to
                let qualified_cols = if let Some(s) = schema {
                    s.get_table(qualifier).map(|(_, ts)| ts.columns.len()).unwrap_or(1)
                } else {
                    1
                };

                if target_col < current_col + qualified_cols {
                    // The position is within this qualified wildcard's columns
                    if let Some(s) = schema {
                        if let Some((_, table_schema)) = s.get_table(qualifier) {
                            let offset = target_col - current_col;
                            if offset < table_schema.columns.len() {
                                return ResolvedPosition::ColumnName(
                                    table_schema.columns[offset].name.clone(),
                                );
                            }
                        }
                    }
                    return ResolvedPosition::NotFound;
                }
                current_col += qualified_cols;
            }
            vibesql_ast::SelectItem::Expression { expr, .. } => {
                if target_col == current_col {
                    return ResolvedPosition::Expression(expr);
                }
                current_col += 1;
            }
        }
    }

    ResolvedPosition::NotFound
}

/// Sort key for ORDER BY: (value, direction, nulls_order, collation)
type SortKey = (
    vibesql_types::SqlValue,
    vibesql_ast::OrderDirection,
    Option<vibesql_ast::NullsOrder>,
    Option<String>,
);

/// Row with optional sort keys for ORDER BY
pub(super) type RowWithSortKeys = (vibesql_storage::Row, Option<Vec<SortKey>>);

/// Count the number of columns in a SELECT list after wildcard expansion
///
/// This correctly handles:
/// - Regular expressions: count as 1 column each
/// - Wildcard (`SELECT *`): expands to all columns from the schema
/// - Qualified wildcards (`SELECT table.*`): expands to all columns from that table
///
/// # Arguments
/// * `select_list` - The SELECT list items
/// * `schema` - Optional schema for wildcard expansion. If None, wildcards count as 1.
fn count_select_columns(
    select_list: &[vibesql_ast::SelectItem],
    schema: Option<&CombinedSchema>,
) -> usize {
    let mut count = 0;
    for item in select_list {
        match item {
            vibesql_ast::SelectItem::Wildcard { .. } => {
                // Expand wildcard to all columns from schema
                if let Some(s) = schema {
                    // Count all columns from all tables in the schema
                    for (_, table_schema) in s.table_schemas.values() {
                        count += table_schema.columns.len();
                    }
                } else {
                    // No schema available, count as 1
                    count += 1;
                }
            }
            vibesql_ast::SelectItem::QualifiedWildcard { qualifier, .. } => {
                // Expand qualified wildcard to all columns from the specified table
                if let Some(s) = schema {
                    if let Some((_, table_schema)) = s.get_table(qualifier) {
                        count += table_schema.columns.len();
                    } else {
                        // Table not found, count as 1 (error will be caught elsewhere)
                        count += 1;
                    }
                } else {
                    // No schema available, count as 1
                    count += 1;
                }
            }
            vibesql_ast::SelectItem::Expression { .. } => {
                count += 1;
            }
        }
    }
    count
}

/// Apply ORDER BY sorting to rows
///
/// Evaluates ORDER BY expressions for each row and sorts them according to the specified
/// directions (ASC/DESC). Supports multi-column sorting with stable sort behavior.
///
/// ORDER BY can reference:
/// - Columns from the FROM clause
/// - Aliases from the SELECT list
/// - Original column names that have been aliased in SELECT
/// - Arbitrary expressions
pub(super) fn apply_order_by(
    mut rows: Vec<RowWithSortKeys>,
    order_by: &[vibesql_ast::OrderByItem],
    evaluator: &CombinedExpressionEvaluator,
    select_list: &[vibesql_ast::SelectItem],
) -> Result<Vec<RowWithSortKeys>, ExecutorError> {
    // Get schema for proper wildcard expansion when counting columns (#4413)
    let schema = evaluator.schema();

    // Evaluate ORDER BY expressions for each row
    for (row, sort_keys) in &mut rows {
        // Clear CSE cache before evaluating this row's ORDER BY expressions
        // to prevent stale cached column values from previous rows
        evaluator.clear_cse_cache();

        let mut keys = Vec::new();
        for (term_index, order_item) in order_by.iter().enumerate() {
            // Check if ORDER BY expression is a SELECT list alias or matches an aliased column
            // Evaluator handles window functions via window_mapping if present
            // Pass schema for proper wildcard expansion in column count validation
            let expr_to_eval =
                resolve_order_by_alias(&order_item.expr, select_list, term_index, Some(schema))?;
            let key_value = evaluator.eval(expr_to_eval.as_ref(), row)?;
            // Get collation for this ORDER BY expression (explicit or inherited from column)
            let collation = evaluator.get_expression_collation(expr_to_eval.as_ref());
            keys.push((key_value, order_item.direction.clone(), order_item.nulls_order, collation));
        }
        *sort_keys = Some(keys);
    }

    // Sort by the evaluated keys (with automatic parallelism based on row count when feature
    // enabled)
    let comparison_fn = |(_, keys_a): &RowWithSortKeys, (_, keys_b): &RowWithSortKeys| {
        let keys_a = keys_a.as_ref().unwrap();
        let keys_b = keys_b.as_ref().unwrap();

        for ((val_a, dir, nulls_order, collation), (val_b, _, _, _)) in
            keys_a.iter().zip(keys_b.iter())
        {
            // Determine NULL ordering:
            // - If explicitly specified via NULLS FIRST/LAST, use that
            // - Default: SQLite treats NULL as smallest value, so:
            //   - ASC: NULL comes first (smallest first)
            //   - DESC: NULL comes last (smallest last)
            let nulls_first = match nulls_order {
                Some(vibesql_ast::NullsOrder::First) => true,
                Some(vibesql_ast::NullsOrder::Last) => false,
                None => matches!(dir, vibesql_ast::OrderDirection::Asc),
            };

            // Handle NULLs according to nulls_first setting
            let cmp = match (val_a.is_null(), val_b.is_null()) {
                (true, true) => Ordering::Equal,
                (true, false) => {
                    if nulls_first {
                        return Ordering::Less; // NULL sorts before non-NULL
                    } else {
                        return Ordering::Greater; // NULL sorts after non-NULL
                    }
                }
                (false, true) => {
                    if nulls_first {
                        return Ordering::Greater; // non-NULL sorts after NULL
                    } else {
                        return Ordering::Less; // non-NULL sorts before NULL
                    }
                }
                (false, false) => {
                    // Apply collation transformation if needed
                    let (cmp_val_a, cmp_val_b) = if let Some(ref coll) = collation {
                        if coll.eq_ignore_ascii_case("nocase") {
                            // For NOCASE collation, uppercase both string values
                            let a = match val_a {
                                vibesql_types::SqlValue::Varchar(s) => {
                                    Cow::Owned(vibesql_types::SqlValue::Varchar(
                                        arcstr::ArcStr::from(s.to_uppercase()),
                                    ))
                                }
                                vibesql_types::SqlValue::Character(s) => {
                                    Cow::Owned(vibesql_types::SqlValue::Character(
                                        arcstr::ArcStr::from(s.to_uppercase()),
                                    ))
                                }
                                other => Cow::Borrowed(other),
                            };
                            let b = match val_b {
                                vibesql_types::SqlValue::Varchar(s) => {
                                    Cow::Owned(vibesql_types::SqlValue::Varchar(
                                        arcstr::ArcStr::from(s.to_uppercase()),
                                    ))
                                }
                                vibesql_types::SqlValue::Character(s) => {
                                    Cow::Owned(vibesql_types::SqlValue::Character(
                                        arcstr::ArcStr::from(s.to_uppercase()),
                                    ))
                                }
                                other => Cow::Borrowed(other),
                            };
                            (a, b)
                        } else {
                            (Cow::Borrowed(val_a), Cow::Borrowed(val_b))
                        }
                    } else {
                        (Cow::Borrowed(val_a), Cow::Borrowed(val_b))
                    };

                    // Compare non-NULL values, respecting direction
                    match dir {
                        vibesql_ast::OrderDirection::Asc => {
                            compare_sql_values(&cmp_val_a, &cmp_val_b)
                        }
                        vibesql_ast::OrderDirection::Desc => {
                            compare_sql_values(&cmp_val_a, &cmp_val_b).reverse()
                        }
                    }
                }
            };

            if cmp != Ordering::Equal {
                return cmp;
            }
        }
        Ordering::Equal
    };

    #[cfg(feature = "parallel")]
    {
        let config = ParallelConfig::global();
        if config.should_parallelize_sort(rows.len()) {
            // Parallel sort for large datasets
            rows.par_sort_by(comparison_fn);
        } else {
            // Sequential sort for small datasets
            rows.sort_by(comparison_fn);
        }
    }

    #[cfg(not(feature = "parallel"))]
    {
        // Always use sequential sort when parallel feature is disabled
        rows.sort_by(comparison_fn);
    }

    Ok(rows)
}

/// Resolve ORDER BY expression for aggregate results to result schema column names
///
/// For aggregate queries, the result schema has columns named by their aliases.
/// This function maps ORDER BY expressions to ColumnRef expressions that can be
/// evaluated against the result schema.
///
/// Handles cases:
/// 1. Numeric position (ORDER BY 1) - returns ColumnRef to the alias/column at that position
/// 2. Alias name (ORDER BY alias) - returns ColumnRef to that alias
/// 3. Original column name (ORDER BY col where col is aliased to alias) - returns ColumnRef to
///    alias
/// 4. Complex expressions containing GROUPING() - recursively resolves sub-expressions
/// 5. Otherwise - returns the original expression (for expressions not matching aliases)
///
/// Returns an error if a numeric column position is out of range (0 or > column count)
///
/// # Arguments
/// * `order_expr` - The ORDER BY expression to resolve
/// * `select_list` - The SELECT list items
/// * `term_index` - 0-indexed position of this ORDER BY term (for error messages)
/// * `schema` - Optional schema for proper wildcard expansion when counting columns (#4413)
pub(crate) fn resolve_order_by_for_aggregates(
    order_expr: &vibesql_ast::Expression,
    select_list: &[vibesql_ast::SelectItem],
    term_index: usize, // 0-indexed position of this ORDER BY term
    schema: Option<&CombinedSchema>,
) -> Result<vibesql_ast::Expression, ExecutorError> {
    // Count actual columns after wildcard expansion (#4413)
    // Note: For aggregate queries, wildcards are typically not present, but we
    // handle them for consistency
    let column_count = count_select_columns(select_list, schema);

    // Validate numeric column positions at the TOP LEVEL ONLY
    // (nested integer literals like `WHERE x = 0` are not column positions)

    // Check for numeric column position (ORDER BY N, ORDER BY +N, ORDER BY -N)
    match extract_column_position(order_expr) {
        ColumnPositionResult::Position(pos) => {
            let idx = validate_column_position(pos, column_count, term_index)?;
            if let Some(col_name) = resolve_position_to_column_name(idx, select_list) {
                return Ok(vibesql_ast::Expression::ColumnRef(
                    vibesql_ast::ColumnIdentifier::simple(&col_name, false),
                ));
            }
        }
        ColumnPositionResult::Negative(pos) => {
            // Negative column positions are always invalid
            return Err(ExecutorError::OrderByOutOfRange {
                term_position: term_index + 1,
                column_number: -pos,
                select_list_len: column_count,
            });
        }
        ColumnPositionResult::NotAPosition => {
            // Not a column position, continue to other resolution logic
        }
    }

    // Delegate to helper that doesn't validate column numbers (for recursive calls)
    Ok(resolve_order_by_for_aggregates_inner(order_expr, select_list))
}

/// Internal helper for recursively resolving ORDER BY expressions.
/// Does NOT validate numeric column positions (validation is done at top level only).
fn resolve_order_by_for_aggregates_inner(
    order_expr: &vibesql_ast::Expression,
    select_list: &[vibesql_ast::SelectItem],
) -> vibesql_ast::Expression {
    // Check for numeric column position (ORDER BY 1, 2, 3, etc.)
    // NOTE: At this point we're in a nested expression, so integer literals are NOT column positions
    if let vibesql_ast::Expression::Literal(vibesql_types::SqlValue::Integer(pos)) = order_expr {
        if *pos > 0 && (*pos as usize) <= select_list.len() {
            let idx = (*pos as usize) - 1;
            if let vibesql_ast::SelectItem::Expression { expr, alias, .. } = &select_list[idx] {
                // Return a ColumnRef to the alias name (or derive from expression)
                let col_name = if let Some(alias_name) = alias {
                    alias_name.clone()
                } else if let vibesql_ast::Expression::ColumnRef(col_id) = expr {
                    col_id.column_canonical().to_string()
                } else if let vibesql_ast::Expression::AggregateFunction { name, .. } = expr {
                    // For aggregate functions, use the function name (lowercase)
                    // This matches the schema column name generated in apply_order_by_to_aggregates
                    name.to_lowercase()
                } else {
                    format!("col{}", idx + 1)
                };
                return vibesql_ast::Expression::ColumnRef(vibesql_ast::ColumnIdentifier::simple(
                    &col_name, false,
                ));
            }
        }
        // If not a valid column position, just return the literal as-is
        return order_expr.clone();
    }

    // Check if ORDER BY expression is a simple column reference (no table qualifier)
    if let vibesql_ast::Expression::ColumnRef(col_id) = order_expr {
        if col_id.schema_canonical().is_none() && col_id.table_canonical().is_none() {
            let column = col_id.column_canonical();
            // First, check if column matches an alias name - return ColumnRef to that alias
            for item in select_list {
                if let vibesql_ast::SelectItem::Expression { alias: Some(alias_name), .. } = item {
                    if alias_name.eq_ignore_ascii_case(column) {
                        // ORDER BY uses alias name, return ColumnRef to that alias
                        return vibesql_ast::Expression::ColumnRef(
                            vibesql_ast::ColumnIdentifier::simple(alias_name, false),
                        );
                    }
                }
            }

            // Second, check if column matches an original column name that has an alias
            for item in select_list {
                if let vibesql_ast::SelectItem::Expression {
                    expr: vibesql_ast::Expression::ColumnRef(select_col_id),
                    alias: Some(alias_name),
                    ..
                } = item
                {
                    if select_col_id.schema_canonical().is_none() {
                        let select_col = select_col_id.column_canonical();
                        if select_col.eq_ignore_ascii_case(column) {
                            // ORDER BY uses original column name, return ColumnRef to the alias
                            return vibesql_ast::Expression::ColumnRef(
                                vibesql_ast::ColumnIdentifier::simple(alias_name, false),
                            );
                        }
                    }
                }
            }

            // Third, check if column matches a SELECT list column without alias
            for item in select_list {
                if let vibesql_ast::SelectItem::Expression {
                    expr: vibesql_ast::Expression::ColumnRef(select_col_id),
                    alias: None,
                    ..
                } = item
                {
                    if select_col_id.schema_canonical().is_none() {
                        let select_col = select_col_id.column_canonical();
                        if select_col.eq_ignore_ascii_case(column) {
                            // Found matching non-aliased column, return as-is
                            return order_expr.clone();
                        }
                    }
                }
            }
        }
    }

    // IMPORTANT: Check if the ENTIRE expression matches any SELECT list expression FIRST
    // This handles cases like GROUPING(a) + GROUPING(b) matching an alias like "lochierarchy"
    // before we try to recursively decompose the expression
    if let Some(alias) = find_matching_select_expression(order_expr, select_list) {
        return vibesql_ast::Expression::ColumnRef(vibesql_ast::ColumnIdentifier::simple(
            &alias, false,
        ));
    }

    // Handle CASE expressions by recursively resolving sub-expressions
    // Use inner helper for recursion (doesn't validate column numbers)
    if let vibesql_ast::Expression::Case { operand, when_clauses, else_result } = order_expr {
        let resolved_operand = operand
            .as_ref()
            .map(|op| Box::new(resolve_order_by_for_aggregates_inner(op, select_list)));

        let mut resolved_when_clauses: Vec<vibesql_ast::CaseWhen> = Vec::new();
        for clause in when_clauses {
            let mut resolved_conditions = Vec::new();
            for cond in &clause.conditions {
                resolved_conditions.push(resolve_order_by_for_aggregates_inner(cond, select_list));
            }
            resolved_when_clauses.push(vibesql_ast::CaseWhen {
                conditions: resolved_conditions,
                result: resolve_order_by_for_aggregates_inner(&clause.result, select_list),
            });
        }

        let resolved_else = else_result
            .as_ref()
            .map(|e| Box::new(resolve_order_by_for_aggregates_inner(e, select_list)));

        return vibesql_ast::Expression::Case {
            operand: resolved_operand,
            when_clauses: resolved_when_clauses,
            else_result: resolved_else,
        };
    }

    // Handle BinaryOp expressions by recursively resolving sub-expressions
    // Try to match the entire binary expression first (already done above with
    // find_matching_select_expression) If no match, try matching each side separately
    if let vibesql_ast::Expression::BinaryOp { left, op, right } = order_expr {
        let resolved_left = resolve_order_by_for_aggregates_inner(left, select_list);
        let resolved_right = resolve_order_by_for_aggregates_inner(right, select_list);

        return vibesql_ast::Expression::BinaryOp {
            left: Box::new(resolved_left),
            op: *op,
            right: Box::new(resolved_right),
        };
    }

    // Handle Function calls (including GROUPING) by checking if they match a SELECT expression
    // This is already handled by find_matching_select_expression above, but keep as fallback
    if let vibesql_ast::Expression::Function { name, .. } = order_expr {
        if name.eq_ignore_ascii_case("GROUPING") || name.eq_ignore_ascii_case("GROUPING_ID") {
            // Try to find a matching GROUPING expression in the SELECT list
            if let Some(alias) = find_matching_select_expression(order_expr, select_list) {
                return vibesql_ast::Expression::ColumnRef(vibesql_ast::ColumnIdentifier::simple(
                    &alias, false,
                ));
            }
        }
    }

    // Not an alias or column position, return the original expression
    order_expr.clone()
}

/// Find a matching expression in the SELECT list and return its alias or generated column name
fn find_matching_select_expression(
    expr: &vibesql_ast::Expression,
    select_list: &[vibesql_ast::SelectItem],
) -> Option<String> {
    for (idx, item) in select_list.iter().enumerate() {
        if let vibesql_ast::SelectItem::Expression { expr: select_expr, alias, .. } = item {
            if expressions_equal(expr, select_expr) {
                // Found matching expression
                // Return alias if present, otherwise derive column name from expression
                return Some(if let Some(alias_name) = alias {
                    alias_name.clone()
                } else if let vibesql_ast::Expression::ColumnRef(col_id) = select_expr {
                    col_id.column_canonical().to_string()
                } else if let vibesql_ast::Expression::AggregateFunction { name, .. } = select_expr
                {
                    // For aggregate functions, use the function name (lowercase)
                    // This matches the schema column name generated in apply_order_by_to_aggregates
                    name.to_lowercase()
                } else {
                    format!("col{}", idx + 1)
                });
            }
        }
    }
    None
}

/// Check if two expressions are structurally equal (for matching ORDER BY expressions to SELECT
/// list)
fn expressions_equal(a: &vibesql_ast::Expression, b: &vibesql_ast::Expression) -> bool {
    match (a, b) {
        (
            vibesql_ast::Expression::ColumnRef(col_id1),
            vibesql_ast::Expression::ColumnRef(col_id2),
        ) => {
            col_id1.schema_canonical().is_none()
                && col_id2.schema_canonical().is_none()
                && col_id1.table_canonical() == col_id2.table_canonical()
                && col_id1.column_canonical() == col_id2.column_canonical()
        }

        (vibesql_ast::Expression::Literal(v1), vibesql_ast::Expression::Literal(v2)) => v1 == v2,

        (
            vibesql_ast::Expression::BinaryOp { left: l1, op: o1, right: r1 },
            vibesql_ast::Expression::BinaryOp { left: l2, op: o2, right: r2 },
        ) => o1 == o2 && expressions_equal(l1, l2) && expressions_equal(r1, r2),

        (
            vibesql_ast::Expression::Function { name: n1, args: a1, .. },
            vibesql_ast::Expression::Function { name: n2, args: a2, .. },
        ) => {
            n1 == n2 // FunctionIdentifier comparison is case-insensitive via canonical
                && a1.len() == a2.len()
                && a1.iter().zip(a2.iter()).all(|(x, y)| expressions_equal(x, y))
        }

        // For other expression types, use debug representation comparison as fallback
        // This is not perfect but handles most common cases
        _ => format!("{:?}", a) == format!("{:?}", b),
    }
}

/// Resolve ORDER BY expression that might be a SELECT list alias or column position
///
/// Handles these cases:
/// 1. Numeric literal (e.g., ORDER BY 1, 2, 3) - returns the expression from that position in
///    SELECT list
/// 2. Simple column reference that matches a SELECT list alias - returns the SELECT list expression
/// 3. Simple column reference that matches an aliased column's original name - returns a ColumnRef
///    to the alias
/// 4. Complex expressions containing alias references (e.g., ORDER BY -x, ORDER BY abs(x)) -
///    recursively resolves alias references within the expression (#4436)
/// 5. Otherwise - returns the original ORDER BY expression
///
/// Returns an error if a numeric column position is out of range (0 or > column count)
///
/// # Arguments
/// * `order_expr` - The ORDER BY expression to resolve
/// * `select_list` - The SELECT list items
/// * `term_index` - 0-indexed position of this ORDER BY term (for error messages)
/// * `schema` - Optional schema for proper wildcard expansion when counting columns (#4413)
pub(crate) fn resolve_order_by_alias<'a>(
    order_expr: &'a vibesql_ast::Expression,
    select_list: &'a [vibesql_ast::SelectItem],
    term_index: usize, // 0-indexed position of this ORDER BY term
    schema: Option<&CombinedSchema>,
) -> Result<Cow<'a, vibesql_ast::Expression>, ExecutorError> {
    // Count actual columns after wildcard expansion (#4413)
    let column_count = count_select_columns(select_list, schema);

    // Check for numeric column position (ORDER BY N, ORDER BY +N, ORDER BY -N)
    match extract_column_position(order_expr) {
        ColumnPositionResult::Position(pos) => {
            let idx = validate_column_position(pos, column_count, term_index)?;

            // Resolve the position, handling wildcard expansion
            match resolve_position_with_wildcards(idx, select_list, schema) {
                ResolvedPosition::Expression(expr) => {
                    return Ok(Cow::Borrowed(expr));
                }
                ResolvedPosition::ColumnName(col_name) => {
                    return Ok(Cow::Owned(vibesql_ast::Expression::ColumnRef(
                        vibesql_ast::ColumnIdentifier::simple(&col_name, false),
                    )));
                }
                ResolvedPosition::NotFound => {
                    // Fallback: shouldn't reach here if validation passed
                }
            }
        }
        ColumnPositionResult::Negative(pos) => {
            // Negative column positions are always invalid
            return Err(ExecutorError::OrderByOutOfRange {
                term_position: term_index + 1,
                column_number: -pos,
                select_list_len: column_count,
            });
        }
        ColumnPositionResult::NotAPosition => {
            // Not a column position, continue to other resolution logic
        }
    }

    // Check if ORDER BY expression is a simple column reference (no table qualifier)
    if let vibesql_ast::Expression::ColumnRef(col_id) = order_expr {
        if col_id.schema_canonical().is_none() && col_id.table_canonical().is_none() {
            let column = col_id.column_canonical();
            // First, search for matching alias in SELECT list (ORDER BY using alias name)
            for item in select_list {
                if let vibesql_ast::SelectItem::Expression {
                    expr, alias: Some(alias_name), ..
                } = item
                {
                    if alias_name.eq_ignore_ascii_case(column) {
                        // Found matching alias, use the SELECT list expression
                        return Ok(Cow::Borrowed(expr));
                    }
                }
            }

            // Second, check if column matches a SELECT list expression that has an alias
            // This handles: SELECT col AS alias ... ORDER BY col
            // HOWEVER: If the column exists in the FROM schema, we should NOT transform it
            // to the alias. The ORDER BY should reference the actual column from the schema.
            //
            // Example: SELECT cnt as tests_affected FROM (SELECT COUNT(*) as cnt ...) sub ORDER BY cnt
            // Here, 'cnt' exists in the subquery schema, so ORDER BY cnt should evaluate 'cnt' directly,
            // not be transformed to 'tests_affected' (which doesn't exist in the schema).
            //
            // Only transform to alias when the column does NOT exist in the FROM schema (rare case).
            let column_exists_in_schema = schema.map_or(false, |s| {
                // Check if column exists in any table in the schema
                s.table_schemas.values().any(|(_start_idx, table_schema)| {
                    table_schema.get_column_index(column).is_some()
                })
            });

            if !column_exists_in_schema {
                for item in select_list {
                    // Check if the SELECT expression is a column reference to the same column
                    if let vibesql_ast::SelectItem::Expression {
                        expr: vibesql_ast::Expression::ColumnRef(select_col_id),
                        alias: Some(alias_name),
                        ..
                    } = item
                    {
                        if select_col_id.schema_canonical().is_none() {
                            let select_col = select_col_id.column_canonical();
                            if select_col.eq_ignore_ascii_case(column) {
                                // The ORDER BY column matches the original column, but it's aliased
                                // Return a new ColumnRef using the alias name
                                return Ok(Cow::Owned(vibesql_ast::Expression::ColumnRef(
                                    vibesql_ast::ColumnIdentifier::simple(alias_name, false),
                                )));
                            }
                        }
                    }
                }
            }
        }
    }

    // For complex expressions (UnaryOp, BinaryOp, Function calls, etc.), recursively resolve
    // alias references within the expression (#4436)
    // This handles cases like: ORDER BY -x, ORDER BY abs(x), ORDER BY 10-x
    if let Some(resolved) = resolve_aliases_in_expression(order_expr, select_list) {
        return Ok(Cow::Owned(resolved));
    }

    // Not an alias or column position, use the original expression
    Ok(Cow::Borrowed(order_expr))
}

/// Recursively resolve alias references within an ORDER BY expression.
///
/// This handles complex expressions like:
/// - `ORDER BY -x` where x is an alias
/// - `ORDER BY abs(x)` where x is an alias
/// - `ORDER BY 10-x` where x is an alias
///
/// Returns Some(resolved_expression) if any aliases were resolved, None otherwise.
fn resolve_aliases_in_expression(
    expr: &vibesql_ast::Expression,
    select_list: &[vibesql_ast::SelectItem],
) -> Option<vibesql_ast::Expression> {
    match expr {
        // Handle UnaryOp (e.g., -x, +x, NOT x)
        vibesql_ast::Expression::UnaryOp { op, expr: inner } => {
            // Try to resolve the inner expression
            resolve_alias_or_clone(inner, select_list).map(|resolved_inner| {
                vibesql_ast::Expression::UnaryOp { op: *op, expr: Box::new(resolved_inner) }
            })
        }

        // Handle BinaryOp (e.g., 10-x, x+y)
        vibesql_ast::Expression::BinaryOp { left, op, right } => {
            let resolved_left = resolve_alias_or_clone(left, select_list);
            let resolved_right = resolve_alias_or_clone(right, select_list);

            // Only return Some if at least one side was resolved
            if resolved_left.is_some() || resolved_right.is_some() {
                Some(vibesql_ast::Expression::BinaryOp {
                    left: Box::new(resolved_left.unwrap_or_else(|| left.as_ref().clone())),
                    op: *op,
                    right: Box::new(resolved_right.unwrap_or_else(|| right.as_ref().clone())),
                })
            } else {
                None
            }
        }

        // Handle Function calls (e.g., abs(x), coalesce(x, 0))
        vibesql_ast::Expression::Function { name, args, character_unit } => {
            let mut any_resolved = false;
            let resolved_args: Vec<_> = args
                .iter()
                .map(|arg| {
                    if let Some(resolved) = resolve_alias_or_clone(arg, select_list) {
                        any_resolved = true;
                        resolved
                    } else {
                        arg.clone()
                    }
                })
                .collect();

            if any_resolved {
                Some(vibesql_ast::Expression::Function {
                    name: name.clone(),
                    args: resolved_args,
                    character_unit: character_unit.clone(),
                })
            } else {
                None
            }
        }

        // Handle CASE expressions
        vibesql_ast::Expression::Case { operand, when_clauses, else_result } => {
            let mut any_resolved = false;

            let resolved_operand = operand.as_ref().map(|op| {
                if let Some(resolved) = resolve_alias_or_clone(op, select_list) {
                    any_resolved = true;
                    Box::new(resolved)
                } else {
                    op.clone()
                }
            });

            let resolved_when_clauses: Vec<_> = when_clauses
                .iter()
                .map(|clause| {
                    let resolved_conditions: Vec<_> = clause
                        .conditions
                        .iter()
                        .map(|cond| {
                            if let Some(resolved) = resolve_alias_or_clone(cond, select_list) {
                                any_resolved = true;
                                resolved
                            } else {
                                cond.clone()
                            }
                        })
                        .collect();

                    let resolved_result = if let Some(resolved) =
                        resolve_alias_or_clone(&clause.result, select_list)
                    {
                        any_resolved = true;
                        resolved
                    } else {
                        clause.result.clone()
                    };

                    vibesql_ast::CaseWhen {
                        conditions: resolved_conditions,
                        result: resolved_result,
                    }
                })
                .collect();

            let resolved_else = else_result.as_ref().map(|e| {
                if let Some(resolved) = resolve_alias_or_clone(e, select_list) {
                    any_resolved = true;
                    Box::new(resolved)
                } else {
                    e.clone()
                }
            });

            if any_resolved {
                Some(vibesql_ast::Expression::Case {
                    operand: resolved_operand,
                    when_clauses: resolved_when_clauses,
                    else_result: resolved_else,
                })
            } else {
                None
            }
        }

        // For other expression types, no resolution needed
        _ => None,
    }
}

/// Helper: resolve an alias in an expression, or return None if no alias was found.
/// Returns Some(resolved_expression) if the expression contains an alias that was resolved.
fn resolve_alias_or_clone(
    expr: &vibesql_ast::Expression,
    select_list: &[vibesql_ast::SelectItem],
) -> Option<vibesql_ast::Expression> {
    // Check if this is a simple column reference that matches an alias
    if let vibesql_ast::Expression::ColumnRef(col_id) = expr {
        if col_id.schema_canonical().is_none() && col_id.table_canonical().is_none() {
            let column = col_id.column_canonical();
            // Search for matching alias in SELECT list
            for item in select_list {
                if let vibesql_ast::SelectItem::Expression {
                    expr: select_expr,
                    alias: Some(alias_name),
                    ..
                } = item
                {
                    if alias_name.eq_ignore_ascii_case(column) {
                        // Found matching alias, return the SELECT list expression
                        return Some(select_expr.clone());
                    }
                }
            }
        }
    }

    // Try recursive resolution for complex expressions
    resolve_aliases_in_expression(expr, select_list)
}

/// Resolve SELECT aliases in WHERE clause expression (SQLite extension).
///
/// SQLite allows referencing SELECT column aliases in WHERE clause, even though
/// standard SQL does not. This function resolves alias references in a WHERE
/// clause expression by replacing them with the actual SELECT expressions.
///
/// Example:
/// ```sql
/// SELECT f1-22 AS x FROM t1 WHERE x > 0
/// -- becomes: SELECT f1-22 AS x FROM t1 WHERE (f1-22) > 0
/// ```
///
/// Returns the resolved expression (cloned with aliases replaced).
pub(crate) fn resolve_where_aliases(
    where_expr: &vibesql_ast::Expression,
    select_list: &[vibesql_ast::SelectItem],
) -> vibesql_ast::Expression {
    // Use empty schema - no table columns to protect from alias resolution
    resolve_where_expression_with_schema(where_expr, select_list, &std::collections::HashSet::new())
}

/// Resolve SELECT aliases in WHERE clause with schema column awareness.
///
/// Same as `resolve_where_aliases`, but also takes a schema to extract table column names.
/// Column names that exist in the table schema will NOT be resolved as aliases.
///
/// **IMPORTANT**: Table column names take precedence over SELECT aliases.
/// If a column name exists in the table schema, it will NOT be resolved as an alias,
/// even if a SELECT alias with the same name exists.
///
/// Example:
/// ```sql
/// SELECT COUNT(*) AS col1 FROM tab0 WHERE col1 > 0
/// -- col1 in WHERE refers to the TABLE COLUMN (tab0.col1), not the alias
/// ```
pub(crate) fn resolve_where_aliases_with_schema(
    where_expr: &vibesql_ast::Expression,
    select_list: &[vibesql_ast::SelectItem],
    schema: &crate::schema::CombinedSchema,
) -> vibesql_ast::Expression {
    // Build set of all column names in the schema (lowercase for case-insensitive matching)
    let table_columns: std::collections::HashSet<String> = schema
        .table_schemas
        .values()
        .flat_map(|(_, table_schema)| table_schema.columns.iter().map(|c| c.name.to_lowercase()))
        .collect();
    resolve_where_expression_with_schema(where_expr, select_list, &table_columns)
}

/// Recursively resolve alias references in a WHERE clause expression.
fn resolve_where_expression_with_schema(
    expr: &vibesql_ast::Expression,
    select_list: &[vibesql_ast::SelectItem],
    table_columns: &std::collections::HashSet<String>,
) -> vibesql_ast::Expression {
    use vibesql_ast::Expression;

    match expr {
        // Column reference: check if it's an alias
        Expression::ColumnRef(col_id)
            if col_id.schema_canonical().is_none() && col_id.table_canonical().is_none() =>
        {
            let column = col_id.column_canonical();
            // SQLite behavior: table column names ALWAYS take precedence over aliases
            // If the column name exists in the table schema, it refers to the table column,
            // not to any SELECT alias with the same name.
            //
            // Example: SELECT COUNT(*) AS col1 FROM tab0 WHERE col1 > 0
            // Here 'col1' in WHERE refers to the TABLE COLUMN (tab0.col1), not the alias
            //
            // Check if this column exists in the table schema
            if table_columns.contains(&column.to_lowercase()) {
                // Column exists in table - don't resolve to alias
                return expr.clone();
            }

            // Fallback: check if any SELECT item is a direct column reference with this name
            // (this is for backward compatibility when no schema is provided)
            for item in select_list {
                if let vibesql_ast::SelectItem::Expression {
                    expr: Expression::ColumnRef(sel_col_id),
                    ..
                } = item
                {
                    if sel_col_id.schema_canonical().is_none()
                        && sel_col_id.table_canonical().is_none()
                    {
                        let col_name = sel_col_id.column_canonical();
                        if col_name.eq_ignore_ascii_case(column) {
                            // The name matches a column reference in SELECT - don't resolve to alias
                            return expr.clone();
                        }
                    }
                    // Also check qualified column references
                    if sel_col_id.schema_canonical().is_none()
                        && sel_col_id.table_canonical().is_some()
                    {
                        let col_name = sel_col_id.column_canonical();
                        if col_name.eq_ignore_ascii_case(column) {
                            // The name matches a column reference in SELECT - don't resolve to alias
                            return expr.clone();
                        }
                    }
                }
            }

            // Now search for matching alias in SELECT list (case-insensitive)
            for item in select_list {
                if let vibesql_ast::SelectItem::Expression {
                    expr: select_expr,
                    alias: Some(alias_name),
                    ..
                } = item
                {
                    if alias_name.eq_ignore_ascii_case(column) {
                        // Found matching alias, return the SELECT expression
                        return select_expr.clone();
                    }
                }
            }
            // Not an alias, return as-is
            expr.clone()
        }

        // Qualified column reference: not an alias, return as-is
        Expression::ColumnRef(col_id)
            if col_id.schema_canonical().is_none() && col_id.table_canonical().is_some() =>
        {
            expr.clone()
        }

        // Schema-qualified column reference: not an alias, return as-is
        Expression::ColumnRef(col_id) if col_id.schema_canonical().is_some() => expr.clone(),

        // Any other ColumnRef case (shouldn't happen, but handle for completeness)
        Expression::ColumnRef(_) => expr.clone(),

        // BinaryOp: resolve both sides
        Expression::BinaryOp { left, op, right } => Expression::BinaryOp {
            left: Box::new(resolve_where_expression_with_schema(left, select_list, table_columns)),
            op: *op,
            right: Box::new(resolve_where_expression_with_schema(
                right,
                select_list,
                table_columns,
            )),
        },

        // UnaryOp: resolve inner expression
        Expression::UnaryOp { op, expr: inner } => Expression::UnaryOp {
            op: *op,
            expr: Box::new(resolve_where_expression_with_schema(inner, select_list, table_columns)),
        },

        // Function call: resolve all arguments
        Expression::Function { name, args, character_unit } => Expression::Function {
            name: name.clone(),
            args: args
                .iter()
                .map(|arg| resolve_where_expression_with_schema(arg, select_list, table_columns))
                .collect(),
            character_unit: character_unit.clone(),
        },

        // CASE expression: resolve all parts
        Expression::Case { operand, when_clauses, else_result } => Expression::Case {
            operand: operand.as_ref().map(|op| {
                Box::new(resolve_where_expression_with_schema(op, select_list, table_columns))
            }),
            when_clauses: when_clauses
                .iter()
                .map(|clause| vibesql_ast::CaseWhen {
                    conditions: clause
                        .conditions
                        .iter()
                        .map(|cond| {
                            resolve_where_expression_with_schema(cond, select_list, table_columns)
                        })
                        .collect(),
                    result: resolve_where_expression_with_schema(
                        &clause.result,
                        select_list,
                        table_columns,
                    ),
                })
                .collect(),
            else_result: else_result.as_ref().map(|e| {
                Box::new(resolve_where_expression_with_schema(e, select_list, table_columns))
            }),
        },

        // IS NULL / IS NOT NULL
        Expression::IsNull { expr: inner, negated } => Expression::IsNull {
            expr: Box::new(resolve_where_expression_with_schema(inner, select_list, table_columns)),
            negated: *negated,
        },

        // IS DISTINCT FROM / IS NOT DISTINCT FROM
        Expression::IsDistinctFrom { left, right, negated } => Expression::IsDistinctFrom {
            left: Box::new(resolve_where_expression_with_schema(left, select_list, table_columns)),
            right: Box::new(resolve_where_expression_with_schema(
                right,
                select_list,
                table_columns,
            )),
            negated: *negated,
        },

        // IS TRUE / IS FALSE / IS UNKNOWN
        Expression::IsTruthValue { expr: inner, truth_value, negated } => {
            Expression::IsTruthValue {
                expr: Box::new(resolve_where_expression_with_schema(
                    inner,
                    select_list,
                    table_columns,
                )),
                truth_value: *truth_value,
                negated: *negated,
            }
        }

        // IN list
        Expression::InList { expr: inner, values, negated } => Expression::InList {
            expr: Box::new(resolve_where_expression_with_schema(inner, select_list, table_columns)),
            values: values
                .iter()
                .map(|v| resolve_where_expression_with_schema(v, select_list, table_columns))
                .collect(),
            negated: *negated,
        },

        // IN subquery: resolve the left expression, leave subquery unchanged
        Expression::In { expr: inner, subquery, negated } => Expression::In {
            expr: Box::new(resolve_where_expression_with_schema(inner, select_list, table_columns)),
            subquery: subquery.clone(),
            negated: *negated,
        },

        // BETWEEN
        Expression::Between { expr: inner, low, high, negated, symmetric } => Expression::Between {
            expr: Box::new(resolve_where_expression_with_schema(inner, select_list, table_columns)),
            low: Box::new(resolve_where_expression_with_schema(low, select_list, table_columns)),
            high: Box::new(resolve_where_expression_with_schema(high, select_list, table_columns)),
            negated: *negated,
            symmetric: *symmetric,
        },

        // LIKE
        Expression::Like { expr: inner, pattern, negated } => Expression::Like {
            expr: Box::new(resolve_where_expression_with_schema(inner, select_list, table_columns)),
            pattern: Box::new(resolve_where_expression_with_schema(
                pattern,
                select_list,
                table_columns,
            )),
            negated: *negated,
        },

        // GLOB
        Expression::Glob { expr: inner, pattern, negated } => Expression::Glob {
            expr: Box::new(resolve_where_expression_with_schema(inner, select_list, table_columns)),
            pattern: Box::new(resolve_where_expression_with_schema(
                pattern,
                select_list,
                table_columns,
            )),
            negated: *negated,
        },

        // CAST
        Expression::Cast { expr: inner, data_type } => Expression::Cast {
            expr: Box::new(resolve_where_expression_with_schema(inner, select_list, table_columns)),
            data_type: data_type.clone(),
        },

        // Conjunction / Disjunction
        Expression::Conjunction(children) => Expression::Conjunction(
            children
                .iter()
                .map(|c| resolve_where_expression_with_schema(c, select_list, table_columns))
                .collect(),
        ),
        Expression::Disjunction(children) => Expression::Disjunction(
            children
                .iter()
                .map(|c| resolve_where_expression_with_schema(c, select_list, table_columns))
                .collect(),
        ),

        // Aggregate functions (resolve arguments)
        Expression::AggregateFunction { name, args, distinct, order_by, filter } => {
            Expression::AggregateFunction {
                name: name.clone(),
                args: args
                    .iter()
                    .map(|arg| {
                        resolve_where_expression_with_schema(arg, select_list, table_columns)
                    })
                    .collect(),
                distinct: *distinct,
                order_by: order_by.as_ref().map(|items| {
                    items
                        .iter()
                        .map(|item| vibesql_ast::OrderByItem {
                            expr: resolve_where_expression_with_schema(
                                &item.expr,
                                select_list,
                                table_columns,
                            ),
                            direction: item.direction.clone(),
                            nulls_order: item.nulls_order,
                        })
                        .collect()
                }),
                filter: filter.as_ref().map(|f| {
                    Box::new(resolve_where_expression_with_schema(f, select_list, table_columns))
                }),
            }
        }

        // RowValueConstructor
        Expression::RowValueConstructor(children) => Expression::RowValueConstructor(
            children
                .iter()
                .map(|c| resolve_where_expression_with_schema(c, select_list, table_columns))
                .collect(),
        ),

        // Collate
        Expression::Collate { expr, collation } => Expression::Collate {
            expr: Box::new(resolve_where_expression_with_schema(expr, select_list, table_columns)),
            collation: collation.clone(),
        },

        // TRIM
        Expression::Trim { position, removal_char, string } => Expression::Trim {
            position: position.clone(),
            removal_char: removal_char.as_ref().map(|c| {
                Box::new(resolve_where_expression_with_schema(c, select_list, table_columns))
            }),
            string: Box::new(resolve_where_expression_with_schema(
                string,
                select_list,
                table_columns,
            )),
        },

        // POSITION
        Expression::Position { substring, string, character_unit } => Expression::Position {
            substring: Box::new(resolve_where_expression_with_schema(
                substring,
                select_list,
                table_columns,
            )),
            string: Box::new(resolve_where_expression_with_schema(
                string,
                select_list,
                table_columns,
            )),
            character_unit: character_unit.clone(),
        },

        // EXTRACT
        Expression::Extract { field, expr: inner } => Expression::Extract {
            field: field.clone(),
            expr: Box::new(resolve_where_expression_with_schema(inner, select_list, table_columns)),
        },

        // INTERVAL
        Expression::Interval { value, unit, leading_precision, fractional_precision } => {
            Expression::Interval {
                value: Box::new(resolve_where_expression_with_schema(
                    value,
                    select_list,
                    table_columns,
                )),
                unit: unit.clone(),
                leading_precision: *leading_precision,
                fractional_precision: *fractional_precision,
            }
        }

        // Quantified comparison
        Expression::QuantifiedComparison { expr: inner, op, quantifier, subquery } => {
            Expression::QuantifiedComparison {
                expr: Box::new(resolve_where_expression_with_schema(
                    inner,
                    select_list,
                    table_columns,
                )),
                op: *op,
                quantifier: quantifier.clone(),
                subquery: subquery.clone(),
            }
        }

        // Expressions that don't need alias resolution (pass through)
        Expression::Literal(_)
        | Expression::Wildcard
        | Expression::CurrentDate
        | Expression::CurrentTime { .. }
        | Expression::CurrentTimestamp { .. }
        | Expression::Default
        | Expression::NextValue { .. }
        | Expression::SessionVariable { .. }
        | Expression::Placeholder(_)
        | Expression::NumberedPlaceholder(_)
        | Expression::NamedPlaceholder(_)
        | Expression::PseudoVariable { .. }
        | Expression::DuplicateKeyValue { .. }
        | Expression::ScalarSubquery(_)
        | Expression::Exists { .. }
        | Expression::WindowFunction { .. }
        | Expression::MatchAgainst { .. } => expr.clone(),
    }
}

/// Extract aggregate expressions from ORDER BY items for pre-computation during GROUP BY.
///
/// When ORDER BY contains aggregate functions (e.g., `ORDER BY max(n)+0`), these aggregates
/// must be computed during the GROUP BY phase, not during ORDER BY evaluation.
/// This function collects all aggregate expressions from ORDER BY so they can be pre-computed.
///
/// Returns a vector of unique aggregate expressions found in ORDER BY.
pub(crate) fn extract_order_by_aggregates(
    order_by: &[vibesql_ast::OrderByItem],
) -> Vec<vibesql_ast::Expression> {
    let mut aggregates = Vec::new();
    for item in order_by {
        collect_aggregates_from_expr(&item.expr, &mut aggregates);
    }
    aggregates
}

/// Recursively collect aggregate function expressions from an expression tree.
fn collect_aggregates_from_expr(
    expr: &vibesql_ast::Expression,
    aggregates: &mut Vec<vibesql_ast::Expression>,
) {
    use vibesql_ast::Expression;

    match expr {
        Expression::AggregateFunction { .. } => {
            // Check if this aggregate is already collected (avoid duplicates)
            let already_exists = aggregates
                .iter()
                .any(|existing| format!("{:?}", existing) == format!("{:?}", expr));
            if !already_exists {
                aggregates.push(expr.clone());
            }
        }

        // Recursively search in compound expressions
        Expression::BinaryOp { left, right, .. } => {
            collect_aggregates_from_expr(left, aggregates);
            collect_aggregates_from_expr(right, aggregates);
        }
        Expression::UnaryOp { expr: inner, .. } => {
            collect_aggregates_from_expr(inner, aggregates);
        }
        Expression::Function { args, .. } => {
            for arg in args {
                collect_aggregates_from_expr(arg, aggregates);
            }
        }
        Expression::Case { operand, when_clauses, else_result } => {
            if let Some(op) = operand {
                collect_aggregates_from_expr(op, aggregates);
            }
            for when_clause in when_clauses {
                for cond in &when_clause.conditions {
                    collect_aggregates_from_expr(cond, aggregates);
                }
                collect_aggregates_from_expr(&when_clause.result, aggregates);
            }
            if let Some(else_expr) = else_result {
                collect_aggregates_from_expr(else_expr, aggregates);
            }
        }
        Expression::Cast { expr: inner, .. } => {
            collect_aggregates_from_expr(inner, aggregates);
        }
        Expression::Between { expr, low, high, .. } => {
            collect_aggregates_from_expr(expr, aggregates);
            collect_aggregates_from_expr(low, aggregates);
            collect_aggregates_from_expr(high, aggregates);
        }
        Expression::InList { expr, values, .. } => {
            collect_aggregates_from_expr(expr, aggregates);
            for item in values {
                collect_aggregates_from_expr(item, aggregates);
            }
        }

        // Leaf expressions - nothing to extract
        Expression::Literal(_)
        | Expression::ColumnRef(_)
        | Expression::Wildcard
        | Expression::CurrentDate
        | Expression::CurrentTime { .. }
        | Expression::CurrentTimestamp { .. }
        | Expression::Default
        | Expression::NextValue { .. }
        | Expression::Placeholder(_)
        | Expression::NumberedPlaceholder(_)
        | Expression::NamedPlaceholder(_)
        | Expression::PseudoVariable { .. }
        | Expression::DuplicateKeyValue { .. }
        | Expression::SessionVariable { .. } => {}

        // Skip subqueries and window functions
        Expression::ScalarSubquery(_)
        | Expression::Exists { .. }
        | Expression::In { .. }
        | Expression::QuantifiedComparison { .. }
        | Expression::WindowFunction { .. } => {}

        // Other expressions we might need to handle
        Expression::Like { expr, pattern, .. } | Expression::Glob { expr, pattern, .. } => {
            collect_aggregates_from_expr(expr, aggregates);
            collect_aggregates_from_expr(pattern, aggregates);
        }
        Expression::IsNull { expr, .. } => {
            collect_aggregates_from_expr(expr, aggregates);
        }
        Expression::IsDistinctFrom { left, right, .. } => {
            collect_aggregates_from_expr(left, aggregates);
            collect_aggregates_from_expr(right, aggregates);
        }
        Expression::IsTruthValue { expr, .. } => {
            collect_aggregates_from_expr(expr, aggregates);
        }
        Expression::Conjunction(terms) | Expression::Disjunction(terms) => {
            for term in terms {
                collect_aggregates_from_expr(term, aggregates);
            }
        }
        Expression::RowValueConstructor(items) => {
            for item in items {
                collect_aggregates_from_expr(item, aggregates);
            }
        }
        Expression::Position { substring, string, .. } => {
            collect_aggregates_from_expr(substring, aggregates);
            collect_aggregates_from_expr(string, aggregates);
        }
        Expression::Trim { string, removal_char, .. } => {
            collect_aggregates_from_expr(string, aggregates);
            if let Some(c) = removal_char {
                collect_aggregates_from_expr(c, aggregates);
            }
        }
        Expression::Extract { expr, .. } => {
            collect_aggregates_from_expr(expr, aggregates);
        }
        Expression::Interval { value, .. } => {
            collect_aggregates_from_expr(value, aggregates);
        }
        Expression::Collate { expr: inner, .. } => {
            collect_aggregates_from_expr(inner, aggregates);
        }
        Expression::MatchAgainst { .. } => {}
    }
}

#[cfg(test)]
mod tests {
    use std::cmp::Ordering;

    use vibesql_storage::Row;
    use vibesql_types::SqlValue;

    use super::*;

    /// Test the comparison function logic with pre-evaluated sort keys
    /// This tests the parallel/sequential sorting logic without needing full evaluator setup
    #[test]
    fn test_sort_with_keys_small_dataset() {
        // Small dataset with pre-populated sort keys
        let mut rows: Vec<RowWithSortKeys> = vec![
            (
                Row::from_vec(vec![SqlValue::Integer(3)]),
                Some(vec![(SqlValue::Integer(3), vibesql_ast::OrderDirection::Asc, None, None)]),
            ),
            (
                Row::from_vec(vec![SqlValue::Integer(1)]),
                Some(vec![(SqlValue::Integer(1), vibesql_ast::OrderDirection::Asc, None, None)]),
            ),
            (
                Row::from_vec(vec![SqlValue::Integer(2)]),
                Some(vec![(SqlValue::Integer(2), vibesql_ast::OrderDirection::Asc, None, None)]),
            ),
        ];

        // Apply sorting logic (mimics what apply_order_by does after key evaluation)
        let comparison_fn = |(_, keys_a): &RowWithSortKeys, (_, keys_b): &RowWithSortKeys| {
            let keys_a = keys_a.as_ref().unwrap();
            let keys_b = keys_b.as_ref().unwrap();

            for ((val_a, dir, _nulls, _coll), (val_b, _, _, _)) in keys_a.iter().zip(keys_b.iter())
            {
                // SQLite treats NULL as smallest value:
                // - ASC: NULL comes first (Less than non-NULL)
                // - DESC: NULL comes last (Greater than non-NULL)
                let cmp = match (val_a.is_null(), val_b.is_null()) {
                    (true, true) => Ordering::Equal,
                    (true, false) => {
                        return if matches!(dir, vibesql_ast::OrderDirection::Asc) {
                            Ordering::Less
                        } else {
                            Ordering::Greater
                        };
                    }
                    (false, true) => {
                        return if matches!(dir, vibesql_ast::OrderDirection::Asc) {
                            Ordering::Greater
                        } else {
                            Ordering::Less
                        };
                    }
                    (false, false) => match dir {
                        vibesql_ast::OrderDirection::Asc => compare_sql_values(val_a, val_b),
                        vibesql_ast::OrderDirection::Desc => {
                            compare_sql_values(val_a, val_b).reverse()
                        }
                    },
                };

                if cmp != Ordering::Equal {
                    return cmp;
                }
            }
            Ordering::Equal
        };

        #[cfg(feature = "parallel")]
        {
            let config = ParallelConfig::global();
            if config.should_parallelize_sort(rows.len()) {
                rows.par_sort_by(comparison_fn);
            } else {
                rows.sort_by(comparison_fn);
            }
        }

        #[cfg(not(feature = "parallel"))]
        {
            rows.sort_by(comparison_fn);
        }

        // Verify sorted order
        assert_eq!(rows[0].0.values[0], SqlValue::Integer(1));
        assert_eq!(rows[1].0.values[0], SqlValue::Integer(2));
        assert_eq!(rows[2].0.values[0], SqlValue::Integer(3));
    }

    #[test]
    fn test_sort_with_keys_large_dataset() {
        // Create large dataset that will trigger parallel path
        let mut rows: Vec<RowWithSortKeys> = Vec::new();
        for i in (0..15000).rev() {
            rows.push((
                Row::from_vec(vec![SqlValue::Integer(i)]),
                Some(vec![(SqlValue::Integer(i), vibesql_ast::OrderDirection::Asc, None, None)]),
            ));
        }

        let comparison_fn = |(_, keys_a): &RowWithSortKeys, (_, keys_b): &RowWithSortKeys| {
            let keys_a = keys_a.as_ref().unwrap();
            let keys_b = keys_b.as_ref().unwrap();

            for ((val_a, dir, _nulls, _coll), (val_b, _, _, _)) in keys_a.iter().zip(keys_b.iter())
            {
                // SQLite treats NULL as smallest value:
                // - ASC: NULL comes first (Less than non-NULL)
                // - DESC: NULL comes last (Greater than non-NULL)
                let cmp = match (val_a.is_null(), val_b.is_null()) {
                    (true, true) => Ordering::Equal,
                    (true, false) => {
                        return if matches!(dir, vibesql_ast::OrderDirection::Asc) {
                            Ordering::Less
                        } else {
                            Ordering::Greater
                        };
                    }
                    (false, true) => {
                        return if matches!(dir, vibesql_ast::OrderDirection::Asc) {
                            Ordering::Greater
                        } else {
                            Ordering::Less
                        };
                    }
                    (false, false) => match dir {
                        vibesql_ast::OrderDirection::Asc => compare_sql_values(val_a, val_b),
                        vibesql_ast::OrderDirection::Desc => {
                            compare_sql_values(val_a, val_b).reverse()
                        }
                    },
                };

                if cmp != Ordering::Equal {
                    return cmp;
                }
            }
            Ordering::Equal
        };

        #[cfg(feature = "parallel")]
        {
            let config = ParallelConfig::global();
            if config.should_parallelize_sort(rows.len()) {
                rows.par_sort_by(comparison_fn);
            } else {
                rows.sort_by(comparison_fn);
            }
        }

        #[cfg(not(feature = "parallel"))]
        {
            rows.sort_by(comparison_fn);
        }

        // Verify first few and last few are correctly sorted
        assert_eq!(rows[0].0.values[0], SqlValue::Integer(0));
        assert_eq!(rows[1].0.values[0], SqlValue::Integer(1));
        assert_eq!(rows[2].0.values[0], SqlValue::Integer(2));
        assert_eq!(rows[14997].0.values[0], SqlValue::Integer(14997));
        assert_eq!(rows[14998].0.values[0], SqlValue::Integer(14998));
        assert_eq!(rows[14999].0.values[0], SqlValue::Integer(14999));
    }

    #[test]
    fn test_sort_descending_with_keys() {
        let mut rows: Vec<RowWithSortKeys> = vec![
            (
                Row::from_vec(vec![SqlValue::Integer(1)]),
                Some(vec![(SqlValue::Integer(1), vibesql_ast::OrderDirection::Desc, None, None)]),
            ),
            (
                Row::from_vec(vec![SqlValue::Integer(3)]),
                Some(vec![(SqlValue::Integer(3), vibesql_ast::OrderDirection::Desc, None, None)]),
            ),
            (
                Row::from_vec(vec![SqlValue::Integer(2)]),
                Some(vec![(SqlValue::Integer(2), vibesql_ast::OrderDirection::Desc, None, None)]),
            ),
        ];

        let comparison_fn = |(_, keys_a): &RowWithSortKeys, (_, keys_b): &RowWithSortKeys| {
            let keys_a = keys_a.as_ref().unwrap();
            let keys_b = keys_b.as_ref().unwrap();

            for ((val_a, dir, _nulls, _coll), (val_b, _, _, _)) in keys_a.iter().zip(keys_b.iter())
            {
                // SQLite treats NULL as smallest value:
                // - ASC: NULL comes first (Less than non-NULL)
                // - DESC: NULL comes last (Greater than non-NULL)
                let cmp = match (val_a.is_null(), val_b.is_null()) {
                    (true, true) => Ordering::Equal,
                    (true, false) => {
                        return if matches!(dir, vibesql_ast::OrderDirection::Asc) {
                            Ordering::Less
                        } else {
                            Ordering::Greater
                        };
                    }
                    (false, true) => {
                        return if matches!(dir, vibesql_ast::OrderDirection::Asc) {
                            Ordering::Greater
                        } else {
                            Ordering::Less
                        };
                    }
                    (false, false) => match dir {
                        vibesql_ast::OrderDirection::Asc => compare_sql_values(val_a, val_b),
                        vibesql_ast::OrderDirection::Desc => {
                            compare_sql_values(val_a, val_b).reverse()
                        }
                    },
                };

                if cmp != Ordering::Equal {
                    return cmp;
                }
            }
            Ordering::Equal
        };

        #[cfg(feature = "parallel")]
        {
            let config = ParallelConfig::global();
            if config.should_parallelize_sort(rows.len()) {
                rows.par_sort_by(comparison_fn);
            } else {
                rows.sort_by(comparison_fn);
            }
        }

        #[cfg(not(feature = "parallel"))]
        {
            rows.sort_by(comparison_fn);
        }

        assert_eq!(rows[0].0.values[0], SqlValue::Integer(3));
        assert_eq!(rows[1].0.values[0], SqlValue::Integer(2));
        assert_eq!(rows[2].0.values[0], SqlValue::Integer(1));
    }

    #[test]
    fn test_sort_with_nulls() {
        // SQLite treats NULL as smallest value:
        // - ASC: NULL comes first
        // - DESC: NULL comes last
        let mut rows_asc: Vec<RowWithSortKeys> = vec![
            (
                Row::from_vec(vec![SqlValue::Integer(2)]),
                Some(vec![(SqlValue::Integer(2), vibesql_ast::OrderDirection::Asc, None, None)]),
            ),
            (
                Row::from_vec(vec![SqlValue::Null]),
                Some(vec![(SqlValue::Null, vibesql_ast::OrderDirection::Asc, None, None)]),
            ),
            (
                Row::from_vec(vec![SqlValue::Integer(1)]),
                Some(vec![(SqlValue::Integer(1), vibesql_ast::OrderDirection::Asc, None, None)]),
            ),
        ];

        let comparison_fn = |(_, keys_a): &RowWithSortKeys, (_, keys_b): &RowWithSortKeys| {
            let keys_a = keys_a.as_ref().unwrap();
            let keys_b = keys_b.as_ref().unwrap();

            for ((val_a, dir, _nulls, _coll), (val_b, _, _, _)) in keys_a.iter().zip(keys_b.iter())
            {
                // SQLite treats NULL as smallest value:
                // - ASC: NULL comes first (Less than non-NULL)
                // - DESC: NULL comes last (Greater than non-NULL)
                let cmp = match (val_a.is_null(), val_b.is_null()) {
                    (true, true) => Ordering::Equal,
                    (true, false) => {
                        return if matches!(dir, vibesql_ast::OrderDirection::Asc) {
                            Ordering::Less
                        } else {
                            Ordering::Greater
                        };
                    }
                    (false, true) => {
                        return if matches!(dir, vibesql_ast::OrderDirection::Asc) {
                            Ordering::Greater
                        } else {
                            Ordering::Less
                        };
                    }
                    (false, false) => match dir {
                        vibesql_ast::OrderDirection::Asc => compare_sql_values(val_a, val_b),
                        vibesql_ast::OrderDirection::Desc => {
                            compare_sql_values(val_a, val_b).reverse()
                        }
                    },
                };

                if cmp != Ordering::Equal {
                    return cmp;
                }
            }
            Ordering::Equal
        };

        rows_asc.sort_by(&comparison_fn);

        // ASC: NULL, 1, 2 (NULLs first, as smallest value)
        assert_eq!(rows_asc[0].0.values[0], SqlValue::Null);
        assert_eq!(rows_asc[1].0.values[0], SqlValue::Integer(1));
        assert_eq!(rows_asc[2].0.values[0], SqlValue::Integer(2));
    }

    #[test]
    #[cfg(feature = "parallel")]
    fn test_parallel_config_threshold() {
        let config = ParallelConfig::global();

        // Verify that parallel sorting is disabled for small datasets
        // (actual threshold depends on hardware, but should be > 100)
        assert!(!config.should_parallelize_sort(100));

        // Verify that parallel sorting is enabled for large datasets
        // (15000 rows should trigger parallel path on any reasonable hardware)
        // Note: On single-core systems this might still be false
        let large_dataset_size = 15000;
        let uses_parallel = config.should_parallelize_sort(large_dataset_size);

        // Just verify the threshold logic is working (result depends on hardware)
        if config.num_threads > 1 {
            // On multi-core, large datasets should use parallel
            assert!(uses_parallel || config.thresholds.sort > large_dataset_size);
        }
    }
}
