/**
 * Migration support for VibeSQL Drizzle adapter
 *
 * This module provides utilities for running Drizzle Kit migrations
 * against a VibeSQL database.
 */

import { readFileSync, readdirSync, existsSync } from 'fs';
import { join, basename } from 'path';
import type { VibeSQLClient } from './types.js';

/**
 * Migration configuration
 */
export interface MigrationConfig {
  /**
   * Path to the migrations folder generated by Drizzle Kit.
   * This folder should contain .sql migration files.
   */
  migrationsFolder: string;

  /**
   * Table name for storing migration metadata.
   * @default '__drizzle_migrations'
   */
  migrationsTable?: string;

  /**
   * Whether to use transactions for each migration.
   * @default true
   */
  useTransactions?: boolean;
}

/**
 * Migration metadata stored in the database
 */
interface MigrationRecord {
  id: number;
  hash: string;
  created_at: number;
}

/**
 * Migration file info
 */
interface MigrationFile {
  name: string;
  hash: string;
  sql: string;
}

/**
 * Simple hash function for migration content
 */
function hashMigration(content: string): string {
  let hash = 0;
  for (let i = 0; i < content.length; i++) {
    const char = content.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;
    hash = hash & hash; // Convert to 32-bit integer
  }
  return Math.abs(hash).toString(16).padStart(8, '0');
}

/**
 * Read and parse migration files from the migrations folder
 */
function readMigrationFiles(migrationsFolder: string): MigrationFile[] {
  if (!existsSync(migrationsFolder)) {
    throw new Error(`Migrations folder not found: ${migrationsFolder}`);
  }

  const files = readdirSync(migrationsFolder)
    .filter((file) => file.endsWith('.sql'))
    .sort(); // Sort by filename (usually timestamp-prefixed)

  return files.map((file) => {
    const content = readFileSync(join(migrationsFolder, file), 'utf-8');
    return {
      name: basename(file, '.sql'),
      hash: hashMigration(content),
      sql: content,
    };
  });
}

/**
 * Ensure the migrations table exists
 */
async function ensureMigrationsTable(
  client: VibeSQLClient,
  tableName: string
): Promise<void> {
  await client.query(`
    CREATE TABLE IF NOT EXISTS "${tableName}" (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      hash TEXT NOT NULL,
      created_at INTEGER NOT NULL DEFAULT (strftime('%s', 'now'))
    )
  `);
}

/**
 * Get already applied migrations
 */
async function getAppliedMigrations(
  client: VibeSQLClient,
  tableName: string
): Promise<Set<string>> {
  const result = await client.query(`SELECT hash FROM "${tableName}"`);
  return new Set(result.rows.map((row: unknown) => (row as { hash: string }).hash));
}

/**
 * Record a migration as applied
 */
async function recordMigration(
  client: VibeSQLClient,
  tableName: string,
  hash: string
): Promise<void> {
  await client.query(`INSERT INTO "${tableName}" (hash) VALUES (?)`, [hash]);
}

/**
 * Run Drizzle Kit migrations against VibeSQL.
 *
 * This function reads migration files from the specified folder
 * (generated by Drizzle Kit's `drizzle-kit generate` command)
 * and applies any pending migrations to the database.
 *
 * @example
 * ```typescript
 * import { VibeSQL } from '@vibesql/client';
 * import { migrate } from '@vibesql/drizzle/migrator';
 *
 * const vibesql = new VibeSQL();
 * await vibesql.connect();
 *
 * await migrate(vibesql, {
 *   migrationsFolder: './drizzle',
 * });
 *
 * console.log('Migrations complete!');
 * ```
 *
 * @example
 * ```typescript
 * // With Drizzle Kit, first generate migrations:
 * // npx drizzle-kit generate:sqlite --schema=./src/schema.ts
 * //
 * // This creates files like:
 * // drizzle/
 * //   0000_initial.sql
 * //   0001_add_users_table.sql
 * //
 * // Then run them:
 * await migrate(vibesql, { migrationsFolder: './drizzle' });
 * ```
 *
 * @param client - VibeSQL client instance
 * @param config - Migration configuration
 * @returns Number of migrations applied
 */
export async function migrate(
  client: VibeSQLClient,
  config: MigrationConfig
): Promise<number> {
  const {
    migrationsFolder,
    migrationsTable = '__drizzle_migrations',
    useTransactions = true,
  } = config;

  // Read migration files
  const migrations = readMigrationFiles(migrationsFolder);

  if (migrations.length === 0) {
    return 0;
  }

  // Ensure migrations table exists
  await ensureMigrationsTable(client, migrationsTable);

  // Get already applied migrations
  const applied = await getAppliedMigrations(client, migrationsTable);

  // Apply pending migrations
  let count = 0;

  for (const migration of migrations) {
    if (applied.has(migration.hash)) {
      continue;
    }

    console.log(`Running migration: ${migration.name}`);

    try {
      if (useTransactions) {
        await client.query('BEGIN TRANSACTION');
      }

      // Execute the migration SQL
      // Split by semicolon for multiple statements
      const statements = migration.sql
        .split(';')
        .map((s) => s.trim())
        .filter((s) => s.length > 0);

      for (const statement of statements) {
        await client.query(statement);
      }

      // Record the migration
      await recordMigration(client, migrationsTable, migration.hash);

      if (useTransactions) {
        await client.query('COMMIT');
      }

      count++;
      console.log(`Completed migration: ${migration.name}`);
    } catch (error) {
      if (useTransactions) {
        await client.query('ROLLBACK');
      }
      throw Object.assign(
        new Error(
          `Migration failed: ${migration.name}\n${error instanceof Error ? error.message : String(error)}`
        ),
        { cause: error }
      );
    }
  }

  return count;
}

/**
 * Get the status of migrations.
 *
 * Returns information about which migrations have been applied
 * and which are pending.
 *
 * @example
 * ```typescript
 * const status = await getMigrationStatus(vibesql, {
 *   migrationsFolder: './drizzle',
 * });
 *
 * console.log('Applied:', status.applied);
 * console.log('Pending:', status.pending);
 * ```
 *
 * @param client - VibeSQL client instance
 * @param config - Migration configuration
 * @returns Migration status
 */
export async function getMigrationStatus(
  client: VibeSQLClient,
  config: Pick<MigrationConfig, 'migrationsFolder' | 'migrationsTable'>
): Promise<{
  applied: string[];
  pending: string[];
  total: number;
}> {
  const { migrationsFolder, migrationsTable = '__drizzle_migrations' } = config;

  // Read migration files
  const migrations = readMigrationFiles(migrationsFolder);

  // Ensure migrations table exists
  await ensureMigrationsTable(client, migrationsTable);

  // Get already applied migrations
  const appliedHashes = await getAppliedMigrations(client, migrationsTable);

  const applied: string[] = [];
  const pending: string[] = [];

  for (const migration of migrations) {
    if (appliedHashes.has(migration.hash)) {
      applied.push(migration.name);
    } else {
      pending.push(migration.name);
    }
  }

  return {
    applied,
    pending,
    total: migrations.length,
  };
}
